<?php

namespace App\Http\Controllers;

use App\Http\Resources\CityResource;
use App\Models\City;
use App\Models\Province;
use Illuminate\Http\Request;

class CityController extends Controller
{

    public function index()
    {
        try {
            $cities = City::orderBy('title')->get();
            return response(CityResource::collection($cities), 200);
        }catch(\Exception $exception){
            return $exception;
        }
    } public function cityProvince($id)
    {
        try {
            $cities = City::orderBy('title')->where('province_id', $id)->get();
            return response(CityResource::collection($cities), 200);
        }catch(\Exception $exception){
            return $exception;
        }
    }

    public function insert(){
        $data = array(
            0 => array('id' => '1', 'title' => 'اسکو', 'province_id' => '1'),
            1 => array('id' => '2', 'title' => 'اهر', 'province_id' => '1'),
            2 => array('id' => '3', 'title' => 'ایلخچی', 'province_id' => '1'),
            3 => array('id' => '4', 'title' => 'آبش احمد', 'province_id' => '1'),
            4 => array('id' => '5', 'title' => 'آذرشهر', 'province_id' => '1'),
            5 => array('id' => '6', 'title' => 'آقکند', 'province_id' => '1'),
            6 => array('id' => '7', 'title' => 'باسمنج', 'province_id' => '1'),
            7 => array('id' => '8', 'title' => 'بخشایش', 'province_id' => '1'),
            8 => array('id' => '9', 'title' => 'بستان آباد', 'province_id' => '1'),
            9 => array('id' => '10', 'title' => 'بناب', 'province_id' => '1'),
            10 => array('id' => '11', 'title' => 'بناب جدید', 'province_id' => '1'),
            11 => array('id' => '12', 'title' => 'تبریز', 'province_id' => '1'),
            12 => array('id' => '13', 'title' => 'ترک', 'province_id' => '1'),
            13 => array('id' => '14', 'title' => 'ترکمانچای', 'province_id' => '1'),
            14 => array('id' => '15', 'title' => 'تسوج', 'province_id' => '1'),
            15 => array('id' => '16', 'title' => 'تیکمه داش', 'province_id' => '1'),
            16 => array('id' => '17', 'title' => 'جلفا', 'province_id' => '1'),
            17 => array('id' => '18', 'title' => 'خاروانا', 'province_id' => '1'),
            18 => array('id' => '19', 'title' => 'خامنه', 'province_id' => '1'),
            19 => array('id' => '20', 'title' => 'خراجو', 'province_id' => '1'),
            20 => array('id' => '21', 'title' => 'خسروشهر', 'province_id' => '1'),
            21 => array('id' => '22', 'title' => 'خضرلو', 'province_id' => '1'),
            22 => array('id' => '23', 'title' => 'خمارلو', 'province_id' => '1'),
            23 => array('id' => '24', 'title' => 'خواجه', 'province_id' => '1'),
            24 => array('id' => '25', 'title' => 'دوزدوزان', 'province_id' => '1'),
            25 => array('id' => '26', 'title' => 'زرنق', 'province_id' => '1'),
            26 => array('id' => '27', 'title' => 'زنوز', 'province_id' => '1'),
            27 => array('id' => '28', 'title' => 'سراب', 'province_id' => '1'),
            28 => array('id' => '29', 'title' => 'سردرود', 'province_id' => '1'),
            29 => array('id' => '30', 'title' => 'سهند', 'province_id' => '1'),
            30 => array('id' => '31', 'title' => 'سیس', 'province_id' => '1'),
            31 => array('id' => '32', 'title' => 'سیه رود', 'province_id' => '1'),
            32 => array('id' => '33', 'title' => 'شبستر', 'province_id' => '1'),
            33 => array('id' => '34', 'title' => 'شربیان', 'province_id' => '1'),
            34 => array('id' => '35', 'title' => 'شرفخانه', 'province_id' => '1'),
            35 => array('id' => '36', 'title' => 'شندآباد', 'province_id' => '1'),
            36 => array('id' => '37', 'title' => 'صوفیان', 'province_id' => '1'),
            37 => array('id' => '38', 'title' => 'عجب شیر', 'province_id' => '1'),
            38 => array('id' => '39', 'title' => 'قره آغاج', 'province_id' => '1'),
            39 => array('id' => '40', 'title' => 'کشکسرای', 'province_id' => '1'),
            40 => array('id' => '41', 'title' => 'کلوانق', 'province_id' => '1'),
            41 => array('id' => '42', 'title' => 'کلیبر', 'province_id' => '1'),
            42 => array('id' => '43', 'title' => 'کوزه کنان', 'province_id' => '1'),
            43 => array('id' => '44', 'title' => 'گوگان', 'province_id' => '1'),
            44 => array('id' => '45', 'title' => 'لیلان', 'province_id' => '1'),
            45 => array('id' => '46', 'title' => 'مراغه', 'province_id' => '1'),
            46 => array('id' => '47', 'title' => 'مرند', 'province_id' => '1'),
            47 => array('id' => '48', 'title' => 'ملکان', 'province_id' => '1'),
            48 => array('id' => '49', 'title' => 'ملک کیان', 'province_id' => '1'),
            49 => array('id' => '50', 'title' => 'ممقان', 'province_id' => '1'),
            50 => array('id' => '51', 'title' => 'مهربان', 'province_id' => '1'),
            51 => array('id' => '52', 'title' => 'میانه', 'province_id' => '1'),
            52 => array('id' => '53', 'title' => 'نظرکهریزی', 'province_id' => '1'),
            53 => array('id' => '54', 'title' => 'هادی شهر', 'province_id' => '1'),
            54 => array('id' => '55', 'title' => 'هرگلان', 'province_id' => '1'),
            55 => array('id' => '56', 'title' => 'هریس', 'province_id' => '1'),
            56 => array('id' => '57', 'title' => 'هشترود', 'province_id' => '1'),
            57 => array('id' => '58', 'title' => 'هوراند', 'province_id' => '1'),
            58 => array('id' => '59', 'title' => 'وایقان', 'province_id' => '1'),
            59 => array('id' => '60', 'title' => 'ورزقان', 'province_id' => '1'),
            60 => array('id' => '61', 'title' => 'یامچی', 'province_id' => '1'),
            61 => array('id' => '62', 'title' => 'ارومیه', 'province_id' => '2'),
            62 => array('id' => '63', 'title' => 'اشنویه', 'province_id' => '2'),
            63 => array('id' => '64', 'title' => 'ایواوغلی', 'province_id' => '2'),
            64 => array('id' => '65', 'title' => 'آواجیق', 'province_id' => '2'),
            65 => array('id' => '66', 'title' => 'باروق', 'province_id' => '2'),
            66 => array('id' => '67', 'title' => 'بازرگان', 'province_id' => '2'),
            67 => array('id' => '68', 'title' => 'بوکان', 'province_id' => '2'),
            68 => array('id' => '69', 'title' => 'پلدشت', 'province_id' => '2'),
            69 => array('id' => '70', 'title' => 'پیرانشهر', 'province_id' => '2'),
            70 => array('id' => '71', 'title' => 'تازه شهر', 'province_id' => '2'),
            71 => array('id' => '72', 'title' => 'تکاب', 'province_id' => '2'),
            72 => array('id' => '73', 'title' => 'چهاربرج', 'province_id' => '2'),
            73 => array('id' => '74', 'title' => 'خوی', 'province_id' => '2'),
            74 => array('id' => '75', 'title' => 'دیزج دیز', 'province_id' => '2'),
            75 => array('id' => '76', 'title' => 'ربط', 'province_id' => '2'),
            76 => array('id' => '77', 'title' => 'سردشت', 'province_id' => '2'),
            77 => array('id' => '78', 'title' => 'سرو', 'province_id' => '2'),
            78 => array('id' => '79', 'title' => 'سلماس', 'province_id' => '2'),
            79 => array('id' => '80', 'title' => 'سیلوانه', 'province_id' => '2'),
            80 => array('id' => '81', 'title' => 'سیمینه', 'province_id' => '2'),
            81 => array('id' => '82', 'title' => 'سیه چشمه', 'province_id' => '2'),
            82 => array('id' => '83', 'title' => 'شاهین دژ', 'province_id' => '2'),
            83 => array('id' => '84', 'title' => 'شوط', 'province_id' => '2'),
            84 => array('id' => '85', 'title' => 'فیرورق', 'province_id' => '2'),
            85 => array('id' => '86', 'title' => 'قره ضیاءالدین', 'province_id' => '2'),
            86 => array('id' => '87', 'title' => 'قطور', 'province_id' => '2'),
            87 => array('id' => '88', 'title' => 'قوشچی', 'province_id' => '2'),
            88 => array('id' => '89', 'title' => 'کشاورز', 'province_id' => '2'),
            89 => array('id' => '90', 'title' => 'گردکشانه', 'province_id' => '2'),
            90 => array('id' => '91', 'title' => 'ماکو', 'province_id' => '2'),
            91 => array('id' => '92', 'title' => 'محمدیار', 'province_id' => '2'),
            92 => array('id' => '93', 'title' => 'محمودآباد', 'province_id' => '2'),
            93 => array('id' => '94', 'title' => 'مهاباد', 'province_id' => '2'),
            94 => array('id' => '95', 'title' => 'میاندوآب', 'province_id' => '2'),
            95 => array('id' => '96', 'title' => 'میرآباد', 'province_id' => '2'),
            96 => array('id' => '97', 'title' => 'نالوس', 'province_id' => '2'),
            97 => array('id' => '98', 'title' => 'نقده', 'province_id' => '2'),
            98 => array('id' => '99', 'title' => 'نوشین', 'province_id' => '2'),
            99 => array('id' => '100', 'title' => 'اردبیل', 'province_id' => '3'),
            100 => array('id' => '101', 'title' => 'اصلاندوز', 'province_id' => '3'),
            101 => array('id' => '102', 'title' => 'آبی بیگلو', 'province_id' => '3'),
            102 => array('id' => '103', 'title' => 'بیله سوار', 'province_id' => '3'),
            103 => array('id' => '104', 'title' => 'پارس آباد', 'province_id' => '3'),
            104 => array('id' => '105', 'title' => 'تازه کند', 'province_id' => '3'),
            105 => array('id' => '106', 'title' => 'تازه کندانگوت', 'province_id' => '3'),
            106 => array('id' => '107', 'title' => 'جعفرآباد', 'province_id' => '3'),
            107 => array('id' => '108', 'title' => 'خلخال', 'province_id' => '3'),
            108 => array('id' => '109', 'title' => 'رضی', 'province_id' => '3'),
            109 => array('id' => '110', 'title' => 'سرعین', 'province_id' => '3'),
            110 => array('id' => '111', 'title' => 'عنبران', 'province_id' => '3'),
            111 => array('id' => '112', 'title' => 'فخرآباد', 'province_id' => '3'),
            112 => array('id' => '113', 'title' => 'کلور', 'province_id' => '3'),
            113 => array('id' => '114', 'title' => 'کوراییم', 'province_id' => '3'),
            114 => array('id' => '115', 'title' => 'گرمی', 'province_id' => '3'),
            115 => array('id' => '116', 'title' => 'گیوی', 'province_id' => '3'),
            116 => array('id' => '117', 'title' => 'لاهرود', 'province_id' => '3'),
            117 => array('id' => '118', 'title' => 'مشگین شهر', 'province_id' => '3'),
            118 => array('id' => '119', 'title' => 'نمین', 'province_id' => '3'),
            119 => array('id' => '120', 'title' => 'نیر', 'province_id' => '3'),
            120 => array('id' => '121', 'title' => 'هشتجین', 'province_id' => '3'),
            121 => array('id' => '122', 'title' => 'هیر', 'province_id' => '3'),
            122 => array('id' => '123', 'title' => 'ابریشم', 'province_id' => '4'),
            123 => array('id' => '124', 'title' => 'ابوزیدآباد', 'province_id' => '4'),
            124 => array('id' => '125', 'title' => 'اردستان', 'province_id' => '4'),
            125 => array('id' => '126', 'title' => 'اژیه', 'province_id' => '4'),
            126 => array('id' => '127', 'title' => 'اصفهان', 'province_id' => '4'),
            127 => array('id' => '128', 'title' => 'افوس', 'province_id' => '4'),
            128 => array('id' => '129', 'title' => 'انارک', 'province_id' => '4'),
            129 => array('id' => '130', 'title' => 'ایمانشهر', 'province_id' => '4'),
            130 => array('id' => '131', 'title' => 'آران وبیدگل', 'province_id' => '4'),
            131 => array('id' => '132', 'title' => 'بادرود', 'province_id' => '4'),
            132 => array('id' => '133', 'title' => 'باغ بهادران', 'province_id' => '4'),
            133 => array('id' => '134', 'title' => 'بافران', 'province_id' => '4'),
            134 => array('id' => '135', 'title' => 'برزک', 'province_id' => '4'),
            135 => array('id' => '136', 'title' => 'برف انبار', 'province_id' => '4'),
            136 => array('id' => '137', 'title' => 'بهاران شهر', 'province_id' => '4'),
            137 => array('id' => '138', 'title' => 'بهارستان', 'province_id' => '4'),
            138 => array('id' => '139', 'title' => 'بوئین و میاندشت', 'province_id' => '4'),
            139 => array('id' => '140', 'title' => 'پیربکران', 'province_id' => '4'),
            140 => array('id' => '141', 'title' => 'تودشک', 'province_id' => '4'),
            141 => array('id' => '142', 'title' => 'تیران', 'province_id' => '4'),
            142 => array('id' => '143', 'title' => 'جندق', 'province_id' => '4'),
            143 => array('id' => '144', 'title' => 'جوزدان', 'province_id' => '4'),
            144 => array('id' => '145', 'title' => 'جوشقان و کامو', 'province_id' => '4'),
            145 => array('id' => '146', 'title' => 'چادگان', 'province_id' => '4'),
            146 => array('id' => '147', 'title' => 'چرمهین', 'province_id' => '4'),
            147 => array('id' => '148', 'title' => 'چمگردان', 'province_id' => '4'),
            148 => array('id' => '149', 'title' => 'حبیب آباد', 'province_id' => '4'),
            149 => array('id' => '150', 'title' => 'حسن آباد', 'province_id' => '4'),
            150 => array('id' => '151', 'title' => 'حنا', 'province_id' => '4'),
            151 => array('id' => '152', 'title' => 'خالدآباد', 'province_id' => '4'),
            152 => array('id' => '153', 'title' => 'خمینی شهر', 'province_id' => '4'),
            153 => array('id' => '154', 'title' => 'خوانسار', 'province_id' => '4'),
            154 => array('id' => '155', 'title' => 'خور', 'province_id' => '4'),
            155 => array('id' => '157', 'title' => 'خورزوق', 'province_id' => '4'),
            156 => array('id' => '158', 'title' => 'داران', 'province_id' => '4'),
            157 => array('id' => '159', 'title' => 'دامنه', 'province_id' => '4'),
            158 => array('id' => '160', 'title' => 'درچه', 'province_id' => '4'),
            159 => array('id' => '161', 'title' => 'دستگرد', 'province_id' => '4'),
            160 => array('id' => '162', 'title' => 'دهاقان', 'province_id' => '4'),
            161 => array('id' => '163', 'title' => 'دهق', 'province_id' => '4'),
            162 => array('id' => '164', 'title' => 'دولت آباد', 'province_id' => '4'),
            163 => array('id' => '165', 'title' => 'دیزیچه', 'province_id' => '4'),
            164 => array('id' => '166', 'title' => 'رزوه', 'province_id' => '4'),
            165 => array('id' => '167', 'title' => 'رضوانشهر', 'province_id' => '4'),
            166 => array('id' => '168', 'title' => 'زاینده رود', 'province_id' => '4'),
            167 => array('id' => '169', 'title' => 'زرین شهر', 'province_id' => '4'),
            168 => array('id' => '170', 'title' => 'زواره', 'province_id' => '4'),
            169 => array('id' => '171', 'title' => 'زیباشهر', 'province_id' => '4'),
            170 => array('id' => '172', 'title' => 'سده لنجان', 'province_id' => '4'),
            171 => array('id' => '173', 'title' => 'سفیدشهر', 'province_id' => '4'),
            172 => array('id' => '174', 'title' => 'سگزی', 'province_id' => '4'),
            173 => array('id' => '175', 'title' => 'سمیرم', 'province_id' => '4'),
            174 => array('id' => '176', 'title' => 'شاهین شهر', 'province_id' => '4'),
            175 => array('id' => '177', 'title' => 'شهرضا', 'province_id' => '4'),
            176 => array('id' => '178', 'title' => 'طالخونچه', 'province_id' => '4'),
            177 => array('id' => '179', 'title' => 'عسگران', 'province_id' => '4'),
            178 => array('id' => '180', 'title' => 'علویجه', 'province_id' => '4'),
            179 => array('id' => '181', 'title' => 'فرخی', 'province_id' => '4'),
            180 => array('id' => '182', 'title' => 'فریدونشهر', 'province_id' => '4'),
            181 => array('id' => '183', 'title' => 'فلاورجان', 'province_id' => '4'),
            182 => array('id' => '184', 'title' => 'فولادشهر', 'province_id' => '4'),
            183 => array('id' => '185', 'title' => 'قمصر', 'province_id' => '4'),
            184 => array('id' => '186', 'title' => 'قهجاورستان', 'province_id' => '4'),
            185 => array('id' => '187', 'title' => 'قهدریجان', 'province_id' => '4'),
            186 => array('id' => '188', 'title' => 'کاشان', 'province_id' => '4'),
            187 => array('id' => '189', 'title' => 'کرکوند', 'province_id' => '4'),
            188 => array('id' => '190', 'title' => 'کلیشاد و سودرجان', 'province_id' => '4'),
            189 => array('id' => '191', 'title' => 'کمشچه', 'province_id' => '4'),
            190 => array('id' => '192', 'title' => 'کمه', 'province_id' => '4'),
            191 => array('id' => '193', 'title' => 'کهریزسنگ', 'province_id' => '4'),
            192 => array('id' => '194', 'title' => 'کوشک', 'province_id' => '4'),
            193 => array('id' => '195', 'title' => 'کوهپایه', 'province_id' => '4'),
            194 => array('id' => '196', 'title' => 'گرگاب', 'province_id' => '4'),
            195 => array('id' => '197', 'title' => 'گزبرخوار', 'province_id' => '4'),
            196 => array('id' => '198', 'title' => 'گلپایگان', 'province_id' => '4'),
            197 => array('id' => '199', 'title' => 'گلدشت', 'province_id' => '4'),
            198 => array('id' => '200', 'title' => 'گلشهر', 'province_id' => '4'),
            199 => array('id' => '201', 'title' => 'گوگد', 'province_id' => '4'),
            200 => array('id' => '202', 'title' => 'لای بید', 'province_id' => '4'),
            201 => array('id' => '203', 'title' => 'مبارکه', 'province_id' => '4'),
            202 => array('id' => '204', 'title' => 'مجلسی', 'province_id' => '4'),
            203 => array('id' => '205', 'title' => 'محمدآباد', 'province_id' => '4'),
            204 => array('id' => '206', 'title' => 'مشکات', 'province_id' => '4'),
            205 => array('id' => '207', 'title' => 'منظریه', 'province_id' => '4'),
            206 => array('id' => '208', 'title' => 'مهاباد', 'province_id' => '4'),
            207 => array('id' => '209', 'title' => 'میمه', 'province_id' => '4'),
            208 => array('id' => '210', 'title' => 'نائین', 'province_id' => '4'),
            209 => array('id' => '211', 'title' => 'نجف آباد', 'province_id' => '4'),
            210 => array('id' => '212', 'title' => 'نصرآباد', 'province_id' => '4'),
            211 => array('id' => '213', 'title' => 'نطنز', 'province_id' => '4'),
            212 => array('id' => '214', 'title' => 'نوش آباد', 'province_id' => '4'),
            213 => array('id' => '215', 'title' => 'نیاسر', 'province_id' => '4'),
            214 => array('id' => '216', 'title' => 'نیک آباد( جرقویه)', 'province_id' => '4'),
            215 => array('id' => '217', 'title' => 'هرند', 'province_id' => '4'),
            216 => array('id' => '218', 'title' => 'ورزنه', 'province_id' => '4'),
            217 => array('id' => '219', 'title' => 'ورنامخواست', 'province_id' => '4'),
            218 => array('id' => '220', 'title' => 'وزوان', 'province_id' => '4'),
            219 => array('id' => '221', 'title' => 'ونک', 'province_id' => '4'),
            220 => array('id' => '222', 'title' => 'اسارا', 'province_id' => '5'),
            221 => array('id' => '223', 'title' => 'اشتهارد', 'province_id' => '5'),
            222 => array('id' => '224', 'title' => 'تنکمان', 'province_id' => '5'),
            223 => array('id' => '225', 'title' => 'چهارباغ', 'province_id' => '5'),
            224 => array('id' => '226', 'title' => 'سعید آباد', 'province_id' => '5'),
            225 => array('id' => '227', 'title' => 'شهر جدید هشتگرد', 'province_id' => '5'),
            226 => array('id' => '228', 'title' => 'طالقان', 'province_id' => '5'),
            227 => array('id' => '229', 'title' => 'کرج', 'province_id' => '5'),
            228 => array('id' => '230', 'title' => 'کمال شهر', 'province_id' => '5'),
            229 => array('id' => '231', 'title' => 'کوهسار', 'province_id' => '5'),
            230 => array('id' => '232', 'title' => 'گرمدره', 'province_id' => '5'),
            231 => array('id' => '233', 'title' => 'ماهدشت', 'province_id' => '5'),
            232 => array('id' => '234', 'title' => 'محمدشهر', 'province_id' => '5'),
            233 => array('id' => '235', 'title' => 'مشکین دشت', 'province_id' => '5'),
            234 => array('id' => '236', 'title' => 'نظرآباد', 'province_id' => '5'),
            235 => array('id' => '237', 'title' => 'هشتگرد', 'province_id' => '5'),
            236 => array('id' => '238', 'title' => 'ارکواز', 'province_id' => '6'),
            237 => array('id' => '239', 'title' => 'ایلام', 'province_id' => '6'),
            238 => array('id' => '240', 'title' => 'ایوان', 'province_id' => '6'),
            239 => array('id' => '241', 'title' => 'آبدانان', 'province_id' => '6'),
            240 => array('id' => '242', 'title' => 'آسمان آباد', 'province_id' => '6'),
            241 => array('id' => '243', 'title' => 'بدره', 'province_id' => '6'),
            242 => array('id' => '244', 'title' => 'پهله', 'province_id' => '6'),
            243 => array('id' => '245', 'title' => 'توحید', 'province_id' => '6'),
            244 => array('id' => '246', 'title' => 'چوار', 'province_id' => '6'),
            245 => array('id' => '247', 'title' => 'دره شهر', 'province_id' => '6'),
            246 => array('id' => '248', 'title' => 'دلگشا', 'province_id' => '6'),
            247 => array('id' => '249', 'title' => 'دهلران', 'province_id' => '6'),
            248 => array('id' => '250', 'title' => 'زرنه', 'province_id' => '6'),
            249 => array('id' => '251', 'title' => 'سراب باغ', 'province_id' => '6'),
            250 => array('id' => '252', 'title' => 'سرابله', 'province_id' => '6'),
            251 => array('id' => '253', 'title' => 'صالح آباد', 'province_id' => '6'),
            252 => array('id' => '254', 'title' => 'لومار', 'province_id' => '6'),
            253 => array('id' => '255', 'title' => 'مهران', 'province_id' => '6'),
            254 => array('id' => '256', 'title' => 'مورموری', 'province_id' => '6'),
            255 => array('id' => '257', 'title' => 'موسیان', 'province_id' => '6'),
            256 => array('id' => '258', 'title' => 'میمه', 'province_id' => '6'),
            257 => array('id' => '259', 'title' => 'امام حسن', 'province_id' => '7'),
            258 => array('id' => '260', 'title' => 'انارستان', 'province_id' => '7'),
            259 => array('id' => '261', 'title' => 'اهرم', 'province_id' => '7'),
            260 => array('id' => '262', 'title' => 'آب پخش', 'province_id' => '7'),
            261 => array('id' => '263', 'title' => 'آبدان', 'province_id' => '7'),
            262 => array('id' => '264', 'title' => 'برازجان', 'province_id' => '7'),
            263 => array('id' => '265', 'title' => 'بردخون', 'province_id' => '7'),
            264 => array('id' => '266', 'title' => 'بندردیر', 'province_id' => '7'),
            265 => array('id' => '267', 'title' => 'بندردیلم', 'province_id' => '7'),
            266 => array('id' => '268', 'title' => 'بندرریگ', 'province_id' => '7'),
            267 => array('id' => '269', 'title' => 'بندرکنگان', 'province_id' => '7'),
            268 => array('id' => '270', 'title' => 'بندرگناوه', 'province_id' => '7'),
            269 => array('id' => '271', 'title' => 'بنک', 'province_id' => '7'),
            270 => array('id' => '272', 'title' => 'بوشهر', 'province_id' => '7'),
            271 => array('id' => '273', 'title' => 'تنگ ارم', 'province_id' => '7'),
            272 => array('id' => '274', 'title' => 'جم', 'province_id' => '7'),
            273 => array('id' => '275', 'title' => 'چغادک', 'province_id' => '7'),
            274 => array('id' => '276', 'title' => 'خارک', 'province_id' => '7'),
            275 => array('id' => '277', 'title' => 'خورموج', 'province_id' => '7'),
            276 => array('id' => '278', 'title' => 'دالکی', 'province_id' => '7'),
            277 => array('id' => '279', 'title' => 'دلوار', 'province_id' => '7'),
            278 => array('id' => '280', 'title' => 'ریز', 'province_id' => '7'),
            279 => array('id' => '281', 'title' => 'سعدآباد', 'province_id' => '7'),
            280 => array('id' => '282', 'title' => 'سیراف', 'province_id' => '7'),
            281 => array('id' => '283', 'title' => 'شبانکاره', 'province_id' => '7'),
            282 => array('id' => '284', 'title' => 'شنبه', 'province_id' => '7'),
            283 => array('id' => '285', 'title' => 'عسلویه', 'province_id' => '7'),
            284 => array('id' => '286', 'title' => 'کاکی', 'province_id' => '7'),
            285 => array('id' => '287', 'title' => 'کلمه', 'province_id' => '7'),
            286 => array('id' => '288', 'title' => 'نخل تقی', 'province_id' => '7'),
            287 => array('id' => '289', 'title' => 'وحدتیه', 'province_id' => '7'),
            288 => array('id' => '290', 'title' => 'ارجمند', 'province_id' => '8'),
            289 => array('id' => '291', 'title' => 'اسلامشهر', 'province_id' => '8'),
            290 => array('id' => '292', 'title' => 'اندیشه', 'province_id' => '8'),
            291 => array('id' => '293', 'title' => 'آبسرد', 'province_id' => '8'),
            292 => array('id' => '294', 'title' => 'آبعلی', 'province_id' => '8'),
            293 => array('id' => '295', 'title' => 'باغستان', 'province_id' => '8'),
            294 => array('id' => '296', 'title' => 'باقرشهر', 'province_id' => '8'),
            295 => array('id' => '297', 'title' => 'بومهن', 'province_id' => '8'),
            296 => array('id' => '298', 'title' => 'پاکدشت', 'province_id' => '8'),
            297 => array('id' => '299', 'title' => 'پردیس', 'province_id' => '8'),
            298 => array('id' => '300', 'title' => 'پیشوا', 'province_id' => '8'),
            299 => array('id' => '301', 'title' => 'تهران', 'province_id' => '8'),
            300 => array('id' => '302', 'title' => 'جوادآباد', 'province_id' => '8'),
            301 => array('id' => '303', 'title' => 'چهاردانگه', 'province_id' => '8'),
            302 => array('id' => '304', 'title' => 'حسن آباد', 'province_id' => '8'),
            303 => array('id' => '305', 'title' => 'دماوند', 'province_id' => '8'),
            304 => array('id' => '306', 'title' => 'دیزین', 'province_id' => '8'),
            305 => array('id' => '307', 'title' => 'شهر ری', 'province_id' => '8'),
            306 => array('id' => '308', 'title' => 'رباط کریم', 'province_id' => '8'),
            307 => array('id' => '309', 'title' => 'رودهن', 'province_id' => '8'),
            308 => array('id' => '310', 'title' => 'شاهدشهر', 'province_id' => '8'),
            309 => array('id' => '311', 'title' => 'شریف آباد', 'province_id' => '8'),
            310 => array('id' => '312', 'title' => 'شمشک', 'province_id' => '8'),
            311 => array('id' => '313', 'title' => 'شهریار', 'province_id' => '8'),
            312 => array('id' => '314', 'title' => 'صالح آباد', 'province_id' => '8'),
            313 => array('id' => '315', 'title' => 'صباشهر', 'province_id' => '8'),
            314 => array('id' => '316', 'title' => 'صفادشت', 'province_id' => '8'),
            315 => array('id' => '317', 'title' => 'فردوسیه', 'province_id' => '8'),
            316 => array('id' => '318', 'title' => 'فشم', 'province_id' => '8'),
            317 => array('id' => '319', 'title' => 'فیروزکوه', 'province_id' => '8'),
            318 => array('id' => '320', 'title' => 'قدس', 'province_id' => '8'),
            319 => array('id' => '321', 'title' => 'قرچک', 'province_id' => '8'),
            320 => array('id' => '322', 'title' => 'کهریزک', 'province_id' => '8'),
            321 => array('id' => '323', 'title' => 'کیلان', 'province_id' => '8'),
            322 => array('id' => '324', 'title' => 'گلستان', 'province_id' => '8'),
            323 => array('id' => '325', 'title' => 'لواسان', 'province_id' => '8'),
            324 => array('id' => '326', 'title' => 'ملارد', 'province_id' => '8'),
            325 => array('id' => '327', 'title' => 'میگون', 'province_id' => '8'),
            326 => array('id' => '328', 'title' => 'نسیم شهر', 'province_id' => '8'),
            327 => array('id' => '329', 'title' => 'نصیرآباد', 'province_id' => '8'),
            328 => array('id' => '330', 'title' => 'وحیدیه', 'province_id' => '8'),
            329 => array('id' => '331', 'title' => 'ورامین', 'province_id' => '8'),
            330 => array('id' => '332', 'title' => 'اردل', 'province_id' => '9'),
            331 => array('id' => '333', 'title' => 'آلونی', 'province_id' => '9'),
            332 => array('id' => '334', 'title' => 'باباحیدر', 'province_id' => '9'),
            333 => array('id' => '335', 'title' => 'بروجن', 'province_id' => '9'),
            334 => array('id' => '336', 'title' => 'بلداجی', 'province_id' => '9'),
            335 => array('id' => '337', 'title' => 'بن', 'province_id' => '9'),
            336 => array('id' => '338', 'title' => 'جونقان', 'province_id' => '9'),
            337 => array('id' => '339', 'title' => 'چلگرد', 'province_id' => '9'),
            338 => array('id' => '340', 'title' => 'سامان', 'province_id' => '9'),
            339 => array('id' => '341', 'title' => 'سفیددشت', 'province_id' => '9'),
            340 => array('id' => '342', 'title' => 'سودجان', 'province_id' => '9'),
            341 => array('id' => '343', 'title' => 'سورشجان', 'province_id' => '9'),
            342 => array('id' => '344', 'title' => 'شلمزار', 'province_id' => '9'),
            343 => array('id' => '345', 'title' => 'شهرکرد', 'province_id' => '9'),
            344 => array('id' => '346', 'title' => 'طاقانک', 'province_id' => '9'),
            345 => array('id' => '347', 'title' => 'فارسان', 'province_id' => '9'),
            346 => array('id' => '348', 'title' => 'فرادنبه', 'province_id' => '9'),
            347 => array('id' => '349', 'title' => 'فرخ شهر', 'province_id' => '9'),
            348 => array('id' => '350', 'title' => 'کیان', 'province_id' => '9'),
            349 => array('id' => '351', 'title' => 'گندمان', 'province_id' => '9'),
            350 => array('id' => '352', 'title' => 'گهرو', 'province_id' => '9'),
            351 => array('id' => '353', 'title' => 'لردگان', 'province_id' => '9'),
            352 => array('id' => '354', 'title' => 'مال خلیفه', 'province_id' => '9'),
            353 => array('id' => '355', 'title' => 'ناغان', 'province_id' => '9'),
            354 => array('id' => '356', 'title' => 'نافچ', 'province_id' => '9'),
            355 => array('id' => '357', 'title' => 'نقنه', 'province_id' => '9'),
            356 => array('id' => '358', 'title' => 'هفشجان', 'province_id' => '9'),
            357 => array('id' => '359', 'title' => 'ارسک', 'province_id' => '10'),
            358 => array('id' => '360', 'title' => 'اسدیه', 'province_id' => '10'),
            359 => array('id' => '361', 'title' => 'اسفدن', 'province_id' => '10'),
            360 => array('id' => '362', 'title' => 'اسلامیه', 'province_id' => '10'),
            361 => array('id' => '363', 'title' => 'آرین شهر', 'province_id' => '10'),
            362 => array('id' => '364', 'title' => 'آیسک', 'province_id' => '10'),
            363 => array('id' => '365', 'title' => 'بشرویه', 'province_id' => '10'),
            364 => array('id' => '366', 'title' => 'بیرجند', 'province_id' => '10'),
            365 => array('id' => '367', 'title' => 'حاجی آباد', 'province_id' => '10'),
            366 => array('id' => '368', 'title' => 'خضری دشت بیاض', 'province_id' => '10'),
            367 => array('id' => '369', 'title' => 'خوسف', 'province_id' => '10'),
            368 => array('id' => '370', 'title' => 'زهان', 'province_id' => '10'),
            369 => array('id' => '371', 'title' => 'سرایان', 'province_id' => '10'),
            370 => array('id' => '372', 'title' => 'سربیشه', 'province_id' => '10'),
            371 => array('id' => '373', 'title' => 'سه قلعه', 'province_id' => '10'),
            372 => array('id' => '374', 'title' => 'شوسف', 'province_id' => '10'),
            373 => array('id' => '375', 'title' => 'طبس', 'province_id' => '10'),
            374 => array('id' => '376', 'title' => 'فردوس', 'province_id' => '10'),
            375 => array('id' => '377', 'title' => 'قاین', 'province_id' => '10'),
            376 => array('id' => '378', 'title' => 'قهستان', 'province_id' => '10'),
            377 => array('id' => '379', 'title' => 'محمدشهر', 'province_id' => '10'),
            378 => array('id' => '380', 'title' => 'مود', 'province_id' => '10'),
            379 => array('id' => '381', 'title' => 'نهبندان', 'province_id' => '10'),
            380 => array('id' => '382', 'title' => 'نیمبلوک', 'province_id' => '10'),
            381 => array('id' => '383', 'title' => 'احمدآباد صولت', 'province_id' => '11'),
            382 => array('id' => '384', 'title' => 'انابد', 'province_id' => '11'),
            383 => array('id' => '385', 'title' => 'باجگیران', 'province_id' => '11'),
            384 => array('id' => '386', 'title' => 'باخرز', 'province_id' => '11'),
            385 => array('id' => '387', 'title' => 'بار', 'province_id' => '11'),
            386 => array('id' => '388', 'title' => 'بایگ', 'province_id' => '11'),
            387 => array('id' => '389', 'title' => 'بجستان', 'province_id' => '11'),
            388 => array('id' => '390', 'title' => 'بردسکن', 'province_id' => '11'),
            389 => array('id' => '391', 'title' => 'بیدخت', 'province_id' => '11'),
            390 => array('id' => '392', 'title' => 'تایباد', 'province_id' => '11'),
            391 => array('id' => '393', 'title' => 'تربت جام', 'province_id' => '11'),
            392 => array('id' => '394', 'title' => 'تربت حیدریه', 'province_id' => '11'),
            393 => array('id' => '395', 'title' => 'جغتای', 'province_id' => '11'),
            394 => array('id' => '396', 'title' => 'جنگل', 'province_id' => '11'),
            395 => array('id' => '397', 'title' => 'چاپشلو', 'province_id' => '11'),
            396 => array('id' => '398', 'title' => 'چکنه', 'province_id' => '11'),
            397 => array('id' => '399', 'title' => 'چناران', 'province_id' => '11'),
            398 => array('id' => '400', 'title' => 'خرو', 'province_id' => '11'),
            399 => array('id' => '401', 'title' => 'خلیل آباد', 'province_id' => '11'),
            400 => array('id' => '402', 'title' => 'خواف', 'province_id' => '11'),
            401 => array('id' => '403', 'title' => 'داورزن', 'province_id' => '11'),
            402 => array('id' => '404', 'title' => 'درگز', 'province_id' => '11'),
            403 => array('id' => '405', 'title' => 'در رود', 'province_id' => '11'),
            404 => array('id' => '406', 'title' => 'دولت آباد', 'province_id' => '11'),
            405 => array('id' => '407', 'title' => 'رباط سنگ', 'province_id' => '11'),
            406 => array('id' => '408', 'title' => 'رشتخوار', 'province_id' => '11'),
            407 => array('id' => '409', 'title' => 'رضویه', 'province_id' => '11'),
            408 => array('id' => '410', 'title' => 'روداب', 'province_id' => '11'),
            409 => array('id' => '411', 'title' => 'ریوش', 'province_id' => '11'),
            410 => array('id' => '412', 'title' => 'سبزوار', 'province_id' => '11'),
            411 => array('id' => '413', 'title' => 'سرخس', 'province_id' => '11'),
            412 => array('id' => '414', 'title' => 'سفیدسنگ', 'province_id' => '11'),
            413 => array('id' => '415', 'title' => 'سلامی', 'province_id' => '11'),
            414 => array('id' => '416', 'title' => 'سلطان آباد', 'province_id' => '11'),
            415 => array('id' => '417', 'title' => 'سنگان', 'province_id' => '11'),
            416 => array('id' => '418', 'title' => 'شادمهر', 'province_id' => '11'),
            417 => array('id' => '419', 'title' => 'شاندیز', 'province_id' => '11'),
            418 => array('id' => '420', 'title' => 'ششتمد', 'province_id' => '11'),
            419 => array('id' => '421', 'title' => 'شهرآباد', 'province_id' => '11'),
            420 => array('id' => '422', 'title' => 'شهرزو', 'province_id' => '11'),
            421 => array('id' => '423', 'title' => 'صالح آباد', 'province_id' => '11'),
            422 => array('id' => '424', 'title' => 'طرقبه', 'province_id' => '11'),
            423 => array('id' => '425', 'title' => 'عشق آباد', 'province_id' => '11'),
            424 => array('id' => '426', 'title' => 'فرهادگرد', 'province_id' => '11'),
            425 => array('id' => '427', 'title' => 'فریمان', 'province_id' => '11'),
            426 => array('id' => '428', 'title' => 'فیروزه', 'province_id' => '11'),
            427 => array('id' => '429', 'title' => 'فیض آباد', 'province_id' => '11'),
            428 => array('id' => '430', 'title' => 'قاسم آباد', 'province_id' => '11'),
            429 => array('id' => '431', 'title' => 'قدمگاه', 'province_id' => '11'),
            430 => array('id' => '432', 'title' => 'قلندرآباد', 'province_id' => '11'),
            431 => array('id' => '433', 'title' => 'قوچان', 'province_id' => '11'),
            432 => array('id' => '434', 'title' => 'کاخک', 'province_id' => '11'),
            433 => array('id' => '435', 'title' => 'کاریز', 'province_id' => '11'),
            434 => array('id' => '436', 'title' => 'کاشمر', 'province_id' => '11'),
            435 => array('id' => '437', 'title' => 'کدکن', 'province_id' => '11'),
            436 => array('id' => '438', 'title' => 'کلات', 'province_id' => '11'),
            437 => array('id' => '439', 'title' => 'کندر', 'province_id' => '11'),
            438 => array('id' => '440', 'title' => 'گلمکان', 'province_id' => '11'),
            439 => array('id' => '441', 'title' => 'گناباد', 'province_id' => '11'),
            440 => array('id' => '442', 'title' => 'لطف آباد', 'province_id' => '11'),
            441 => array('id' => '443', 'title' => 'مزدآوند', 'province_id' => '11'),
            442 => array('id' => '444', 'title' => 'مشهد', 'province_id' => '11'),
            443 => array('id' => '445', 'title' => 'ملک آباد', 'province_id' => '11'),
            444 => array('id' => '446', 'title' => 'نشتیفان', 'province_id' => '11'),
            445 => array('id' => '447', 'title' => 'نصرآباد', 'province_id' => '11'),
            446 => array('id' => '448', 'title' => 'نقاب', 'province_id' => '11'),
            447 => array('id' => '449', 'title' => 'نوخندان', 'province_id' => '11'),
            448 => array('id' => '450', 'title' => 'نیشابور', 'province_id' => '11'),
            449 => array('id' => '451', 'title' => 'نیل شهر', 'province_id' => '11'),
            450 => array('id' => '452', 'title' => 'همت آباد', 'province_id' => '11'),
            451 => array('id' => '453', 'title' => 'یونسی', 'province_id' => '11'),
            452 => array('id' => '454', 'title' => 'اسفراین', 'province_id' => '12'),
            453 => array('id' => '455', 'title' => 'ایور', 'province_id' => '12'),
            454 => array('id' => '456', 'title' => 'آشخانه', 'province_id' => '12'),
            455 => array('id' => '457', 'title' => 'بجنورد', 'province_id' => '12'),
            456 => array('id' => '458', 'title' => 'پیش قلعه', 'province_id' => '12'),
            457 => array('id' => '459', 'title' => 'تیتکانلو', 'province_id' => '12'),
            458 => array('id' => '460', 'title' => 'جاجرم', 'province_id' => '12'),
            459 => array('id' => '461', 'title' => 'حصارگرمخان', 'province_id' => '12'),
            460 => array('id' => '462', 'title' => 'درق', 'province_id' => '12'),
            461 => array('id' => '463', 'title' => 'راز', 'province_id' => '12'),
            462 => array('id' => '464', 'title' => 'سنخواست', 'province_id' => '12'),
            463 => array('id' => '465', 'title' => 'شوقان', 'province_id' => '12'),
            464 => array('id' => '466', 'title' => 'شیروان', 'province_id' => '12'),
            465 => array('id' => '467', 'title' => 'صفی آباد', 'province_id' => '12'),
            466 => array('id' => '468', 'title' => 'فاروج', 'province_id' => '12'),
            467 => array('id' => '469', 'title' => 'قاضی', 'province_id' => '12'),
            468 => array('id' => '470', 'title' => 'گرمه', 'province_id' => '12'),
            469 => array('id' => '471', 'title' => 'لوجلی', 'province_id' => '12'),
            470 => array('id' => '472', 'title' => 'اروندکنار', 'province_id' => '13'),
            471 => array('id' => '473', 'title' => 'الوان', 'province_id' => '13'),
            472 => array('id' => '474', 'title' => 'امیدیه', 'province_id' => '13'),
            473 => array('id' => '475', 'title' => 'اندیمشک', 'province_id' => '13'),
            474 => array('id' => '476', 'title' => 'اهواز', 'province_id' => '13'),
            475 => array('id' => '477', 'title' => 'ایذه', 'province_id' => '13'),
            476 => array('id' => '478', 'title' => 'آبادان', 'province_id' => '13'),
            477 => array('id' => '479', 'title' => 'آغاجاری', 'province_id' => '13'),
            478 => array('id' => '480', 'title' => 'باغ ملک', 'province_id' => '13'),
            479 => array('id' => '481', 'title' => 'بستان', 'province_id' => '13'),
            480 => array('id' => '482', 'title' => 'بندرامام خمینی', 'province_id' => '13'),
            481 => array('id' => '483', 'title' => 'بندرماهشهر', 'province_id' => '13'),
            482 => array('id' => '484', 'title' => 'بهبهان', 'province_id' => '13'),
            483 => array('id' => '485', 'title' => 'ترکالکی', 'province_id' => '13'),
            484 => array('id' => '486', 'title' => 'جایزان', 'province_id' => '13'),
            485 => array('id' => '487', 'title' => 'چمران', 'province_id' => '13'),
            486 => array('id' => '488', 'title' => 'چویبده', 'province_id' => '13'),
            487 => array('id' => '489', 'title' => 'حر', 'province_id' => '13'),
            488 => array('id' => '490', 'title' => 'حسینیه', 'province_id' => '13'),
            489 => array('id' => '491', 'title' => 'حمزه', 'province_id' => '13'),
            490 => array('id' => '492', 'title' => 'حمیدیه', 'province_id' => '13'),
            491 => array('id' => '493', 'title' => 'خرمشهر', 'province_id' => '13'),
            492 => array('id' => '494', 'title' => 'دارخوین', 'province_id' => '13'),
            493 => array('id' => '495', 'title' => 'دزآب', 'province_id' => '13'),
            494 => array('id' => '496', 'title' => 'دزفول', 'province_id' => '13'),
            495 => array('id' => '497', 'title' => 'دهدز', 'province_id' => '13'),
            496 => array('id' => '498', 'title' => 'رامشیر', 'province_id' => '13'),
            497 => array('id' => '499', 'title' => 'رامهرمز', 'province_id' => '13'),
            498 => array('id' => '500', 'title' => 'رفیع', 'province_id' => '13'),
            499 => array('id' => '501', 'title' => 'زهره', 'province_id' => '13'),
            500 => array('id' => '502', 'title' => 'سالند', 'province_id' => '13'),
            501 => array('id' => '503', 'title' => 'سردشت', 'province_id' => '13'),
            502 => array('id' => '504', 'title' => 'سوسنگرد', 'province_id' => '13'),
            503 => array('id' => '505', 'title' => 'شادگان', 'province_id' => '13'),
            504 => array('id' => '506', 'title' => 'شاوور', 'province_id' => '13'),
            505 => array('id' => '507', 'title' => 'شرافت', 'province_id' => '13'),
            506 => array('id' => '508', 'title' => 'شوش', 'province_id' => '13'),
            507 => array('id' => '509', 'title' => 'شوشتر', 'province_id' => '13'),
            508 => array('id' => '510', 'title' => 'شیبان', 'province_id' => '13'),
            509 => array('id' => '511', 'title' => 'صالح شهر', 'province_id' => '13'),
            510 => array('id' => '512', 'title' => 'صفی آباد', 'province_id' => '13'),
            511 => array('id' => '513', 'title' => 'صیدون', 'province_id' => '13'),
            512 => array('id' => '514', 'title' => 'قلعه تل', 'province_id' => '13'),
            513 => array('id' => '515', 'title' => 'قلعه خواجه', 'province_id' => '13'),
            514 => array('id' => '516', 'title' => 'گتوند', 'province_id' => '13'),
            515 => array('id' => '517', 'title' => 'لالی', 'province_id' => '13'),
            516 => array('id' => '518', 'title' => 'مسجدسلیمان', 'province_id' => '13'),
            517 => array('id' => '520', 'title' => 'ملاثانی', 'province_id' => '13'),
            518 => array('id' => '521', 'title' => 'میانرود', 'province_id' => '13'),
            519 => array('id' => '522', 'title' => 'مینوشهر', 'province_id' => '13'),
            520 => array('id' => '523', 'title' => 'هفتگل', 'province_id' => '13'),
            521 => array('id' => '524', 'title' => 'هندیجان', 'province_id' => '13'),
            522 => array('id' => '525', 'title' => 'هویزه', 'province_id' => '13'),
            523 => array('id' => '526', 'title' => 'ویس', 'province_id' => '13'),
            524 => array('id' => '527', 'title' => 'ابهر', 'province_id' => '14'),
            525 => array('id' => '528', 'title' => 'ارمغان خانه', 'province_id' => '14'),
            526 => array('id' => '529', 'title' => 'آب بر', 'province_id' => '14'),
            527 => array('id' => '530', 'title' => 'چورزق', 'province_id' => '14'),
            528 => array('id' => '531', 'title' => 'حلب', 'province_id' => '14'),
            529 => array('id' => '532', 'title' => 'خرمدره', 'province_id' => '14'),
            530 => array('id' => '533', 'title' => 'دندی', 'province_id' => '14'),
            531 => array('id' => '534', 'title' => 'زرین آباد', 'province_id' => '14'),
            532 => array('id' => '535', 'title' => 'زرین رود', 'province_id' => '14'),
            533 => array('id' => '536', 'title' => 'زنجان', 'province_id' => '14'),
            534 => array('id' => '537', 'title' => 'سجاس', 'province_id' => '14'),
            535 => array('id' => '538', 'title' => 'سلطانیه', 'province_id' => '14'),
            536 => array('id' => '539', 'title' => 'سهرورد', 'province_id' => '14'),
            537 => array('id' => '540', 'title' => 'صائین قلعه', 'province_id' => '14'),
            538 => array('id' => '541', 'title' => 'قیدار', 'province_id' => '14'),
            539 => array('id' => '542', 'title' => 'گرماب', 'province_id' => '14'),
            540 => array('id' => '543', 'title' => 'ماه نشان', 'province_id' => '14'),
            541 => array('id' => '544', 'title' => 'هیدج', 'province_id' => '14'),
            542 => array('id' => '545', 'title' => 'امیریه', 'province_id' => '15'),
            543 => array('id' => '546', 'title' => 'ایوانکی', 'province_id' => '15'),
            544 => array('id' => '547', 'title' => 'آرادان', 'province_id' => '15'),
            545 => array('id' => '548', 'title' => 'بسطام', 'province_id' => '15'),
            546 => array('id' => '549', 'title' => 'بیارجمند', 'province_id' => '15'),
            547 => array('id' => '550', 'title' => 'دامغان', 'province_id' => '15'),
            548 => array('id' => '551', 'title' => 'درجزین', 'province_id' => '15'),
            549 => array('id' => '552', 'title' => 'دیباج', 'province_id' => '15'),
            550 => array('id' => '553', 'title' => 'سرخه', 'province_id' => '15'),
            551 => array('id' => '554', 'title' => 'سمنان', 'province_id' => '15'),
            552 => array('id' => '555', 'title' => 'شاهرود', 'province_id' => '15'),
            553 => array('id' => '556', 'title' => 'شهمیرزاد', 'province_id' => '15'),
            554 => array('id' => '557', 'title' => 'کلاته خیج', 'province_id' => '15'),
            555 => array('id' => '558', 'title' => 'گرمسار', 'province_id' => '15'),
            556 => array('id' => '559', 'title' => 'مجن', 'province_id' => '15'),
            557 => array('id' => '560', 'title' => 'مهدی شهر', 'province_id' => '15'),
            558 => array('id' => '561', 'title' => 'میامی', 'province_id' => '15'),
            559 => array('id' => '562', 'title' => 'ادیمی', 'province_id' => '16'),
            560 => array('id' => '563', 'title' => 'اسپکه', 'province_id' => '16'),
            561 => array('id' => '564', 'title' => 'ایرانشهر', 'province_id' => '16'),
            562 => array('id' => '565', 'title' => 'بزمان', 'province_id' => '16'),
            563 => array('id' => '566', 'title' => 'بمپور', 'province_id' => '16'),
            564 => array('id' => '567', 'title' => 'بنت', 'province_id' => '16'),
            565 => array('id' => '568', 'title' => 'بنجار', 'province_id' => '16'),
            566 => array('id' => '569', 'title' => 'پیشین', 'province_id' => '16'),
            567 => array('id' => '570', 'title' => 'جالق', 'province_id' => '16'),
            568 => array('id' => '571', 'title' => 'چابهار', 'province_id' => '16'),
            569 => array('id' => '572', 'title' => 'خاش', 'province_id' => '16'),
            570 => array('id' => '573', 'title' => 'دوست محمد', 'province_id' => '16'),
            571 => array('id' => '574', 'title' => 'راسک', 'province_id' => '16'),
            572 => array('id' => '575', 'title' => 'زابل', 'province_id' => '16'),
            573 => array('id' => '576', 'title' => 'زابلی', 'province_id' => '16'),
            574 => array('id' => '577', 'title' => 'زاهدان', 'province_id' => '16'),
            575 => array('id' => '578', 'title' => 'زهک', 'province_id' => '16'),
            576 => array('id' => '579', 'title' => 'سراوان', 'province_id' => '16'),
            577 => array('id' => '580', 'title' => 'سرباز', 'province_id' => '16'),
            578 => array('id' => '581', 'title' => 'سوران', 'province_id' => '16'),
            579 => array('id' => '582', 'title' => 'سیرکان', 'province_id' => '16'),
            580 => array('id' => '583', 'title' => 'علی اکبر', 'province_id' => '16'),
            581 => array('id' => '584', 'title' => 'فنوج', 'province_id' => '16'),
            582 => array('id' => '585', 'title' => 'قصرقند', 'province_id' => '16'),
            583 => array('id' => '586', 'title' => 'کنارک', 'province_id' => '16'),
            584 => array('id' => '587', 'title' => 'گشت', 'province_id' => '16'),
            585 => array('id' => '588', 'title' => 'گلمورتی', 'province_id' => '16'),
            586 => array('id' => '589', 'title' => 'محمدان', 'province_id' => '16'),
            587 => array('id' => '590', 'title' => 'محمدآباد', 'province_id' => '16'),
            588 => array('id' => '591', 'title' => 'محمدی', 'province_id' => '16'),
            589 => array('id' => '592', 'title' => 'میرجاوه', 'province_id' => '16'),
            590 => array('id' => '593', 'title' => 'نصرت آباد', 'province_id' => '16'),
            591 => array('id' => '594', 'title' => 'نگور', 'province_id' => '16'),
            592 => array('id' => '595', 'title' => 'نوک آباد', 'province_id' => '16'),
            593 => array('id' => '596', 'title' => 'نیک شهر', 'province_id' => '16'),
            594 => array('id' => '597', 'title' => 'هیدوچ', 'province_id' => '16'),
            595 => array('id' => '598', 'title' => 'اردکان', 'province_id' => '17'),
            596 => array('id' => '599', 'title' => 'ارسنجان', 'province_id' => '17'),
            597 => array('id' => '600', 'title' => 'استهبان', 'province_id' => '17'),
            598 => array('id' => '601', 'title' => 'اشکنان', 'province_id' => '17'),
            599 => array('id' => '602', 'title' => 'افزر', 'province_id' => '17'),
            600 => array('id' => '603', 'title' => 'اقلید', 'province_id' => '17'),
            601 => array('id' => '604', 'title' => 'امام شهر', 'province_id' => '17'),
            602 => array('id' => '605', 'title' => 'اهل', 'province_id' => '17'),
            603 => array('id' => '606', 'title' => 'اوز', 'province_id' => '17'),
            604 => array('id' => '607', 'title' => 'ایج', 'province_id' => '17'),
            605 => array('id' => '608', 'title' => 'ایزدخواست', 'province_id' => '17'),
            606 => array('id' => '609', 'title' => 'آباده', 'province_id' => '17'),
            607 => array('id' => '610', 'title' => 'آباده طشک', 'province_id' => '17'),
            608 => array('id' => '611', 'title' => 'باب انار', 'province_id' => '17'),
            609 => array('id' => '612', 'title' => 'بالاده', 'province_id' => '17'),
            610 => array('id' => '613', 'title' => 'بنارویه', 'province_id' => '17'),
            611 => array('id' => '614', 'title' => 'بهمن', 'province_id' => '17'),
            612 => array('id' => '615', 'title' => 'بوانات', 'province_id' => '17'),
            613 => array('id' => '616', 'title' => 'بیرم', 'province_id' => '17'),
            614 => array('id' => '617', 'title' => 'بیضا', 'province_id' => '17'),
            615 => array('id' => '618', 'title' => 'جنت شهر', 'province_id' => '17'),
            616 => array('id' => '619', 'title' => 'جهرم', 'province_id' => '17'),
            617 => array('id' => '620', 'title' => 'جویم', 'province_id' => '17'),
            618 => array('id' => '621', 'title' => 'زرین دشت', 'province_id' => '17'),
            619 => array('id' => '622', 'title' => 'حسن آباد', 'province_id' => '17'),
            620 => array('id' => '623', 'title' => 'خان زنیان', 'province_id' => '17'),
            621 => array('id' => '624', 'title' => 'خاوران', 'province_id' => '17'),
            622 => array('id' => '625', 'title' => 'خرامه', 'province_id' => '17'),
            623 => array('id' => '626', 'title' => 'خشت', 'province_id' => '17'),
            624 => array('id' => '627', 'title' => 'خنج', 'province_id' => '17'),
            625 => array('id' => '628', 'title' => 'خور', 'province_id' => '17'),
            626 => array('id' => '629', 'title' => 'داراب', 'province_id' => '17'),
            627 => array('id' => '630', 'title' => 'داریان', 'province_id' => '17'),
            628 => array('id' => '631', 'title' => 'دبیران', 'province_id' => '17'),
            629 => array('id' => '632', 'title' => 'دژکرد', 'province_id' => '17'),
            630 => array('id' => '633', 'title' => 'دهرم', 'province_id' => '17'),
            631 => array('id' => '634', 'title' => 'دوبرجی', 'province_id' => '17'),
            632 => array('id' => '635', 'title' => 'رامجرد', 'province_id' => '17'),
            633 => array('id' => '636', 'title' => 'رونیز', 'province_id' => '17'),
            634 => array('id' => '637', 'title' => 'زاهدشهر', 'province_id' => '17'),
            635 => array('id' => '638', 'title' => 'زرقان', 'province_id' => '17'),
            636 => array('id' => '639', 'title' => 'سده', 'province_id' => '17'),
            637 => array('id' => '640', 'title' => 'سروستان', 'province_id' => '17'),
            638 => array('id' => '641', 'title' => 'سعادت شهر', 'province_id' => '17'),
            639 => array('id' => '642', 'title' => 'سورمق', 'province_id' => '17'),
            640 => array('id' => '643', 'title' => 'سپیدان', 'province_id' => '17'),
            641 => array('id' => '644', 'title' => 'ششده', 'province_id' => '17'),
            642 => array('id' => '645', 'title' => 'شهرپیر', 'province_id' => '17'),
            643 => array('id' => '646', 'title' => 'شهرصدرا', 'province_id' => '17'),
            644 => array('id' => '647', 'title' => 'شیراز', 'province_id' => '17'),
            645 => array('id' => '648', 'title' => 'صغاد', 'province_id' => '17'),
            646 => array('id' => '649', 'title' => 'صفاشهر', 'province_id' => '17'),
            647 => array('id' => '650', 'title' => 'علامرودشت', 'province_id' => '17'),
            648 => array('id' => '651', 'title' => 'فدامی', 'province_id' => '17'),
            649 => array('id' => '652', 'title' => 'فراشبند', 'province_id' => '17'),
            650 => array('id' => '653', 'title' => 'فسا', 'province_id' => '17'),
            651 => array('id' => '654', 'title' => 'فیروزآباد', 'province_id' => '17'),
            652 => array('id' => '655', 'title' => 'قائمیه', 'province_id' => '17'),
            653 => array('id' => '656', 'title' => 'قادرآباد', 'province_id' => '17'),
            654 => array('id' => '657', 'title' => 'قطب آباد', 'province_id' => '17'),
            655 => array('id' => '658', 'title' => 'قطرویه', 'province_id' => '17'),
            656 => array('id' => '659', 'title' => 'قیر', 'province_id' => '17'),
            657 => array('id' => '660', 'title' => 'کارزین (فتح آباد)', 'province_id' => '17'),
            658 => array('id' => '661', 'title' => 'کازرون', 'province_id' => '17'),
            659 => array('id' => '662', 'title' => 'کامفیروز', 'province_id' => '17'),
            660 => array('id' => '663', 'title' => 'کره ای', 'province_id' => '17'),
            661 => array('id' => '664', 'title' => 'کنارتخته', 'province_id' => '17'),
            662 => array('id' => '665', 'title' => 'کوار', 'province_id' => '17'),
            663 => array('id' => '666', 'title' => 'گراش', 'province_id' => '17'),
            664 => array('id' => '667', 'title' => 'گله دار', 'province_id' => '17'),
            665 => array('id' => '668', 'title' => 'لار', 'province_id' => '17'),
            666 => array('id' => '669', 'title' => 'لامرد', 'province_id' => '17'),
            667 => array('id' => '670', 'title' => 'لپویی', 'province_id' => '17'),
            668 => array('id' => '671', 'title' => 'لطیفی', 'province_id' => '17'),
            669 => array('id' => '672', 'title' => 'مبارک آباددیز', 'province_id' => '17'),
            670 => array('id' => '673', 'title' => 'مرودشت', 'province_id' => '17'),
            671 => array('id' => '674', 'title' => 'مشکان', 'province_id' => '17'),
            672 => array('id' => '675', 'title' => 'مصیری', 'province_id' => '17'),
            673 => array('id' => '676', 'title' => 'مهر', 'province_id' => '17'),
            674 => array('id' => '677', 'title' => 'میمند', 'province_id' => '17'),
            675 => array('id' => '678', 'title' => 'نوبندگان', 'province_id' => '17'),
            676 => array('id' => '679', 'title' => 'نوجین', 'province_id' => '17'),
            677 => array('id' => '680', 'title' => 'نودان', 'province_id' => '17'),
            678 => array('id' => '681', 'title' => 'نورآباد', 'province_id' => '17'),
            679 => array('id' => '682', 'title' => 'نی ریز', 'province_id' => '17'),
            680 => array('id' => '683', 'title' => 'وراوی', 'province_id' => '17'),
            681 => array('id' => '684', 'title' => 'ارداق', 'province_id' => '18'),
            682 => array('id' => '685', 'title' => 'اسفرورین', 'province_id' => '18'),
            683 => array('id' => '686', 'title' => 'اقبالیه', 'province_id' => '18'),
            684 => array('id' => '687', 'title' => 'الوند', 'province_id' => '18'),
            685 => array('id' => '688', 'title' => 'آبگرم', 'province_id' => '18'),
            686 => array('id' => '689', 'title' => 'آبیک', 'province_id' => '18'),
            687 => array('id' => '690', 'title' => 'آوج', 'province_id' => '18'),
            688 => array('id' => '691', 'title' => 'بوئین زهرا', 'province_id' => '18'),
            689 => array('id' => '692', 'title' => 'بیدستان', 'province_id' => '18'),
            690 => array('id' => '693', 'title' => 'تاکستان', 'province_id' => '18'),
            691 => array('id' => '694', 'title' => 'خاکعلی', 'province_id' => '18'),
            692 => array('id' => '695', 'title' => 'خرمدشت', 'province_id' => '18'),
            693 => array('id' => '696', 'title' => 'دانسفهان', 'province_id' => '18'),
            694 => array('id' => '697', 'title' => 'رازمیان', 'province_id' => '18'),
            695 => array('id' => '698', 'title' => 'سگزآباد', 'province_id' => '18'),
            696 => array('id' => '699', 'title' => 'سیردان', 'province_id' => '18'),
            697 => array('id' => '700', 'title' => 'شال', 'province_id' => '18'),
            698 => array('id' => '701', 'title' => 'شریفیه', 'province_id' => '18'),
            699 => array('id' => '702', 'title' => 'ضیاآباد', 'province_id' => '18'),
            700 => array('id' => '703', 'title' => 'قزوین', 'province_id' => '18'),
            701 => array('id' => '704', 'title' => 'کوهین', 'province_id' => '18'),
            702 => array('id' => '705', 'title' => 'محمدیه', 'province_id' => '18'),
            703 => array('id' => '706', 'title' => 'محمودآباد نمونه', 'province_id' => '18'),
            704 => array('id' => '707', 'title' => 'معلم کلایه', 'province_id' => '18'),
            705 => array('id' => '708', 'title' => 'نرجه', 'province_id' => '18'),
            706 => array('id' => '709', 'title' => 'جعفریه', 'province_id' => '19'),
            707 => array('id' => '710', 'title' => 'دستجرد', 'province_id' => '19'),
            708 => array('id' => '711', 'title' => 'سلفچگان', 'province_id' => '19'),
            709 => array('id' => '712', 'title' => 'قم', 'province_id' => '19'),
            710 => array('id' => '713', 'title' => 'قنوات', 'province_id' => '19'),
            711 => array('id' => '714', 'title' => 'کهک', 'province_id' => '19'),
            712 => array('id' => '715', 'title' => 'آرمرده', 'province_id' => '20'),
            713 => array('id' => '716', 'title' => 'بابارشانی', 'province_id' => '20'),
            714 => array('id' => '717', 'title' => 'بانه', 'province_id' => '20'),
            715 => array('id' => '718', 'title' => 'بلبان آباد', 'province_id' => '20'),
            716 => array('id' => '719', 'title' => 'بوئین سفلی', 'province_id' => '20'),
            717 => array('id' => '720', 'title' => 'بیجار', 'province_id' => '20'),
            718 => array('id' => '721', 'title' => 'چناره', 'province_id' => '20'),
            719 => array('id' => '722', 'title' => 'دزج', 'province_id' => '20'),
            720 => array('id' => '723', 'title' => 'دلبران', 'province_id' => '20'),
            721 => array('id' => '724', 'title' => 'دهگلان', 'province_id' => '20'),
            722 => array('id' => '725', 'title' => 'دیواندره', 'province_id' => '20'),
            723 => array('id' => '726', 'title' => 'زرینه', 'province_id' => '20'),
            724 => array('id' => '727', 'title' => 'سروآباد', 'province_id' => '20'),
            725 => array('id' => '728', 'title' => 'سریش آباد', 'province_id' => '20'),
            726 => array('id' => '729', 'title' => 'سقز', 'province_id' => '20'),
            727 => array('id' => '730', 'title' => 'سنندج', 'province_id' => '20'),
            728 => array('id' => '731', 'title' => 'شویشه', 'province_id' => '20'),
            729 => array('id' => '732', 'title' => 'صاحب', 'province_id' => '20'),
            730 => array('id' => '733', 'title' => 'قروه', 'province_id' => '20'),
            731 => array('id' => '734', 'title' => 'کامیاران', 'province_id' => '20'),
            732 => array('id' => '735', 'title' => 'کانی دینار', 'province_id' => '20'),
            733 => array('id' => '736', 'title' => 'کانی سور', 'province_id' => '20'),
            734 => array('id' => '737', 'title' => 'مریوان', 'province_id' => '20'),
            735 => array('id' => '738', 'title' => 'موچش', 'province_id' => '20'),
            736 => array('id' => '739', 'title' => 'یاسوکند', 'province_id' => '20'),
            737 => array('id' => '740', 'title' => 'اختیارآباد', 'province_id' => '21'),
            738 => array('id' => '741', 'title' => 'ارزوئیه', 'province_id' => '21'),
            739 => array('id' => '742', 'title' => 'امین شهر', 'province_id' => '21'),
            740 => array('id' => '743', 'title' => 'انار', 'province_id' => '21'),
            741 => array('id' => '744', 'title' => 'اندوهجرد', 'province_id' => '21'),
            742 => array('id' => '745', 'title' => 'باغین', 'province_id' => '21'),
            743 => array('id' => '746', 'title' => 'بافت', 'province_id' => '21'),
            744 => array('id' => '747', 'title' => 'بردسیر', 'province_id' => '21'),
            745 => array('id' => '748', 'title' => 'بروات', 'province_id' => '21'),
            746 => array('id' => '749', 'title' => 'بزنجان', 'province_id' => '21'),
            747 => array('id' => '750', 'title' => 'بم', 'province_id' => '21'),
            748 => array('id' => '751', 'title' => 'بهرمان', 'province_id' => '21'),
            749 => array('id' => '752', 'title' => 'پاریز', 'province_id' => '21'),
            750 => array('id' => '753', 'title' => 'جبالبارز', 'province_id' => '21'),
            751 => array('id' => '754', 'title' => 'جوپار', 'province_id' => '21'),
            752 => array('id' => '755', 'title' => 'جوزم', 'province_id' => '21'),
            753 => array('id' => '756', 'title' => 'جیرفت', 'province_id' => '21'),
            754 => array('id' => '757', 'title' => 'چترود', 'province_id' => '21'),
            755 => array('id' => '758', 'title' => 'خاتون آباد', 'province_id' => '21'),
            756 => array('id' => '759', 'title' => 'خانوک', 'province_id' => '21'),
            757 => array('id' => '760', 'title' => 'خورسند', 'province_id' => '21'),
            758 => array('id' => '761', 'title' => 'درب بهشت', 'province_id' => '21'),
            759 => array('id' => '762', 'title' => 'دهج', 'province_id' => '21'),
            760 => array('id' => '763', 'title' => 'رابر', 'province_id' => '21'),
            761 => array('id' => '764', 'title' => 'راور', 'province_id' => '21'),
            762 => array('id' => '765', 'title' => 'راین', 'province_id' => '21'),
            763 => array('id' => '766', 'title' => 'رفسنجان', 'province_id' => '21'),
            764 => array('id' => '767', 'title' => 'رودبار', 'province_id' => '21'),
            765 => array('id' => '768', 'title' => 'ریحان شهر', 'province_id' => '21'),
            766 => array('id' => '769', 'title' => 'زرند', 'province_id' => '21'),
            767 => array('id' => '770', 'title' => 'زنگی آباد', 'province_id' => '21'),
            768 => array('id' => '771', 'title' => 'زیدآباد', 'province_id' => '21'),
            769 => array('id' => '772', 'title' => 'سیرجان', 'province_id' => '21'),
            770 => array('id' => '773', 'title' => 'شهداد', 'province_id' => '21'),
            771 => array('id' => '774', 'title' => 'شهربابک', 'province_id' => '21'),
            772 => array('id' => '775', 'title' => 'صفائیه', 'province_id' => '21'),
            773 => array('id' => '776', 'title' => 'عنبرآباد', 'province_id' => '21'),
            774 => array('id' => '777', 'title' => 'فاریاب', 'province_id' => '21'),
            775 => array('id' => '778', 'title' => 'فهرج', 'province_id' => '21'),
            776 => array('id' => '779', 'title' => 'قلعه گنج', 'province_id' => '21'),
            777 => array('id' => '780', 'title' => 'کاظم آباد', 'province_id' => '21'),
            778 => array('id' => '781', 'title' => 'کرمان', 'province_id' => '21'),
            779 => array('id' => '782', 'title' => 'کشکوئیه', 'province_id' => '21'),
            780 => array('id' => '783', 'title' => 'کهنوج', 'province_id' => '21'),
            781 => array('id' => '784', 'title' => 'کوهبنان', 'province_id' => '21'),
            782 => array('id' => '785', 'title' => 'کیانشهر', 'province_id' => '21'),
            783 => array('id' => '786', 'title' => 'گلباف', 'province_id' => '21'),
            784 => array('id' => '787', 'title' => 'گلزار', 'province_id' => '21'),
            785 => array('id' => '788', 'title' => 'لاله زار', 'province_id' => '21'),
            786 => array('id' => '789', 'title' => 'ماهان', 'province_id' => '21'),
            787 => array('id' => '790', 'title' => 'محمدآباد', 'province_id' => '21'),
            788 => array('id' => '791', 'title' => 'محی آباد', 'province_id' => '21'),
            789 => array('id' => '792', 'title' => 'مردهک', 'province_id' => '21'),
            790 => array('id' => '793', 'title' => 'مس سرچشمه', 'province_id' => '21'),
            791 => array('id' => '794', 'title' => 'منوجان', 'province_id' => '21'),
            792 => array('id' => '795', 'title' => 'نجف شهر', 'province_id' => '21'),
            793 => array('id' => '796', 'title' => 'نرماشیر', 'province_id' => '21'),
            794 => array('id' => '797', 'title' => 'نظام شهر', 'province_id' => '21'),
            795 => array('id' => '798', 'title' => 'نگار', 'province_id' => '21'),
            796 => array('id' => '799', 'title' => 'نودژ', 'province_id' => '21'),
            797 => array('id' => '800', 'title' => 'هجدک', 'province_id' => '21'),
            798 => array('id' => '801', 'title' => 'یزدان شهر', 'province_id' => '21'),
            799 => array('id' => '802', 'title' => 'ازگله', 'province_id' => '22'),
            800 => array('id' => '803', 'title' => 'اسلام آباد غرب', 'province_id' => '22'),
            801 => array('id' => '804', 'title' => 'باینگان', 'province_id' => '22'),
            802 => array('id' => '805', 'title' => 'بیستون', 'province_id' => '22'),
            803 => array('id' => '806', 'title' => 'پاوه', 'province_id' => '22'),
            804 => array('id' => '807', 'title' => 'تازه آباد', 'province_id' => '22'),
            805 => array('id' => '808', 'title' => 'جوان رود', 'province_id' => '22'),
            806 => array('id' => '809', 'title' => 'حمیل', 'province_id' => '22'),
            807 => array('id' => '810', 'title' => 'ماهیدشت', 'province_id' => '22'),
            808 => array('id' => '811', 'title' => 'روانسر', 'province_id' => '22'),
            809 => array('id' => '812', 'title' => 'سرپل ذهاب', 'province_id' => '22'),
            810 => array('id' => '813', 'title' => 'سرمست', 'province_id' => '22'),
            811 => array('id' => '814', 'title' => 'سطر', 'province_id' => '22'),
            812 => array('id' => '815', 'title' => 'سنقر', 'province_id' => '22'),
            813 => array('id' => '816', 'title' => 'سومار', 'province_id' => '22'),
            814 => array('id' => '817', 'title' => 'شاهو', 'province_id' => '22'),
            815 => array('id' => '818', 'title' => 'صحنه', 'province_id' => '22'),
            816 => array('id' => '819', 'title' => 'قصرشیرین', 'province_id' => '22'),
            817 => array('id' => '820', 'title' => 'کرمانشاه', 'province_id' => '22'),
            818 => array('id' => '821', 'title' => 'کرندغرب', 'province_id' => '22'),
            819 => array('id' => '822', 'title' => 'کنگاور', 'province_id' => '22'),
            820 => array('id' => '823', 'title' => 'کوزران', 'province_id' => '22'),
            821 => array('id' => '824', 'title' => 'گهواره', 'province_id' => '22'),
            822 => array('id' => '825', 'title' => 'گیلانغرب', 'province_id' => '22'),
            823 => array('id' => '826', 'title' => 'میان راهان', 'province_id' => '22'),
            824 => array('id' => '827', 'title' => 'نودشه', 'province_id' => '22'),
            825 => array('id' => '828', 'title' => 'نوسود', 'province_id' => '22'),
            826 => array('id' => '829', 'title' => 'هرسین', 'province_id' => '22'),
            827 => array('id' => '830', 'title' => 'هلشی', 'province_id' => '22'),
            828 => array('id' => '831', 'title' => 'باشت', 'province_id' => '23'),
            829 => array('id' => '832', 'title' => 'پاتاوه', 'province_id' => '23'),
            830 => array('id' => '833', 'title' => 'چرام', 'province_id' => '23'),
            831 => array('id' => '834', 'title' => 'چیتاب', 'province_id' => '23'),
            832 => array('id' => '835', 'title' => 'دهدشت', 'province_id' => '23'),
            833 => array('id' => '836', 'title' => 'دوگنبدان', 'province_id' => '23'),
            834 => array('id' => '837', 'title' => 'دیشموک', 'province_id' => '23'),
            835 => array('id' => '838', 'title' => 'سوق', 'province_id' => '23'),
            836 => array('id' => '839', 'title' => 'سی سخت', 'province_id' => '23'),
            837 => array('id' => '840', 'title' => 'قلعه رئیسی', 'province_id' => '23'),
            838 => array('id' => '841', 'title' => 'گراب سفلی', 'province_id' => '23'),
            839 => array('id' => '842', 'title' => 'لنده', 'province_id' => '23'),
            840 => array('id' => '843', 'title' => 'لیکک', 'province_id' => '23'),
            841 => array('id' => '844', 'title' => 'مادوان', 'province_id' => '23'),
            842 => array('id' => '845', 'title' => 'مارگون', 'province_id' => '23'),
            843 => array('id' => '846', 'title' => 'یاسوج', 'province_id' => '23'),
            844 => array('id' => '847', 'title' => 'انبارآلوم', 'province_id' => '24'),
            845 => array('id' => '848', 'title' => 'اینچه برون', 'province_id' => '24'),
            846 => array('id' => '849', 'title' => 'آزادشهر', 'province_id' => '24'),
            847 => array('id' => '850', 'title' => 'آق قلا', 'province_id' => '24'),
            848 => array('id' => '851', 'title' => 'بندرترکمن', 'province_id' => '24'),
            849 => array('id' => '852', 'title' => 'بندرگز', 'province_id' => '24'),
            850 => array('id' => '853', 'title' => 'جلین', 'province_id' => '24'),
            851 => array('id' => '854', 'title' => 'خان ببین', 'province_id' => '24'),
            852 => array('id' => '855', 'title' => 'دلند', 'province_id' => '24'),
            853 => array('id' => '856', 'title' => 'رامیان', 'province_id' => '24'),
            854 => array('id' => '857', 'title' => 'سرخنکلاته', 'province_id' => '24'),
            855 => array('id' => '858', 'title' => 'سیمین شهر', 'province_id' => '24'),
            856 => array('id' => '859', 'title' => 'علی آباد کتول', 'province_id' => '24'),
            857 => array('id' => '860', 'title' => 'فاضل آباد', 'province_id' => '24'),
            858 => array('id' => '861', 'title' => 'کردکوی', 'province_id' => '24'),
            859 => array('id' => '862', 'title' => 'کلاله', 'province_id' => '24'),
            860 => array('id' => '863', 'title' => 'گالیکش', 'province_id' => '24'),
            861 => array('id' => '864', 'title' => 'گرگان', 'province_id' => '24'),
            862 => array('id' => '865', 'title' => 'گمیش تپه', 'province_id' => '24'),
            863 => array('id' => '866', 'title' => 'گنبدکاووس', 'province_id' => '24'),
            864 => array('id' => '867', 'title' => 'مراوه', 'province_id' => '24'),
            865 => array('id' => '868', 'title' => 'مینودشت', 'province_id' => '24'),
            866 => array('id' => '869', 'title' => 'نگین شهر', 'province_id' => '24'),
            867 => array('id' => '870', 'title' => 'نوده خاندوز', 'province_id' => '24'),
            868 => array('id' => '871', 'title' => 'نوکنده', 'province_id' => '24'),
            869 => array('id' => '872', 'title' => 'ازنا', 'province_id' => '25'),
            870 => array('id' => '873', 'title' => 'اشترینان', 'province_id' => '25'),
            871 => array('id' => '874', 'title' => 'الشتر', 'province_id' => '25'),
            872 => array('id' => '875', 'title' => 'الیگودرز', 'province_id' => '25'),
            873 => array('id' => '876', 'title' => 'بروجرد', 'province_id' => '25'),
            874 => array('id' => '877', 'title' => 'پلدختر', 'province_id' => '25'),
            875 => array('id' => '878', 'title' => 'چالانچولان', 'province_id' => '25'),
            876 => array('id' => '879', 'title' => 'چغلوندی', 'province_id' => '25'),
            877 => array('id' => '880', 'title' => 'چقابل', 'province_id' => '25'),
            878 => array('id' => '881', 'title' => 'خرم آباد', 'province_id' => '25'),
            879 => array('id' => '882', 'title' => 'درب گنبد', 'province_id' => '25'),
            880 => array('id' => '883', 'title' => 'دورود', 'province_id' => '25'),
            881 => array('id' => '884', 'title' => 'زاغه', 'province_id' => '25'),
            882 => array('id' => '885', 'title' => 'سپیددشت', 'province_id' => '25'),
            883 => array('id' => '886', 'title' => 'سراب دوره', 'province_id' => '25'),
            884 => array('id' => '887', 'title' => 'فیروزآباد', 'province_id' => '25'),
            885 => array('id' => '888', 'title' => 'کونانی', 'province_id' => '25'),
            886 => array('id' => '889', 'title' => 'کوهدشت', 'province_id' => '25'),
            887 => array('id' => '890', 'title' => 'گراب', 'province_id' => '25'),
            888 => array('id' => '891', 'title' => 'معمولان', 'province_id' => '25'),
            889 => array('id' => '892', 'title' => 'مومن آباد', 'province_id' => '25'),
            890 => array('id' => '893', 'title' => 'نورآباد', 'province_id' => '25'),
            891 => array('id' => '894', 'title' => 'ویسیان', 'province_id' => '25'),
            892 => array('id' => '895', 'title' => 'احمدسرگوراب', 'province_id' => '26'),
            893 => array('id' => '896', 'title' => 'اسالم', 'province_id' => '26'),
            894 => array('id' => '897', 'title' => 'اطاقور', 'province_id' => '26'),
            895 => array('id' => '898', 'title' => 'املش', 'province_id' => '26'),
            896 => array('id' => '899', 'title' => 'آستارا', 'province_id' => '26'),
            897 => array('id' => '900', 'title' => 'آستانه اشرفیه', 'province_id' => '26'),
            898 => array('id' => '901', 'title' => 'بازار جمعه', 'province_id' => '26'),
            899 => array('id' => '902', 'title' => 'بره سر', 'province_id' => '26'),
            900 => array('id' => '903', 'title' => 'بندرانزلی', 'province_id' => '26'),
            901 => array('id' => '906', 'title' => 'پره سر', 'province_id' => '26'),
            902 => array('id' => '907', 'title' => 'تالش', 'province_id' => '26'),
            903 => array('id' => '908', 'title' => 'توتکابن', 'province_id' => '26'),
            904 => array('id' => '909', 'title' => 'جیرنده', 'province_id' => '26'),
            905 => array('id' => '910', 'title' => 'چابکسر', 'province_id' => '26'),
            906 => array('id' => '911', 'title' => 'چاف و چمخاله', 'province_id' => '26'),
            907 => array('id' => '912', 'title' => 'چوبر', 'province_id' => '26'),
            908 => array('id' => '913', 'title' => 'حویق', 'province_id' => '26'),
            909 => array('id' => '914', 'title' => 'خشکبیجار', 'province_id' => '26'),
            910 => array('id' => '915', 'title' => 'خمام', 'province_id' => '26'),
            911 => array('id' => '916', 'title' => 'دیلمان', 'province_id' => '26'),
            912 => array('id' => '917', 'title' => 'رانکوه', 'province_id' => '26'),
            913 => array('id' => '918', 'title' => 'رحیم آباد', 'province_id' => '26'),
            914 => array('id' => '919', 'title' => 'رستم آباد', 'province_id' => '26'),
            915 => array('id' => '920', 'title' => 'رشت', 'province_id' => '26'),
            916 => array('id' => '921', 'title' => 'رضوانشهر', 'province_id' => '26'),
            917 => array('id' => '922', 'title' => 'رودبار', 'province_id' => '26'),
            918 => array('id' => '923', 'title' => 'رودبنه', 'province_id' => '26'),
            919 => array('id' => '924', 'title' => 'رودسر', 'province_id' => '26'),
            920 => array('id' => '925', 'title' => 'سنگر', 'province_id' => '26'),
            921 => array('id' => '926', 'title' => 'سیاهکل', 'province_id' => '26'),
            922 => array('id' => '927', 'title' => 'شفت', 'province_id' => '26'),
            923 => array('id' => '928', 'title' => 'شلمان', 'province_id' => '26'),
            924 => array('id' => '929', 'title' => 'صومعه سرا', 'province_id' => '26'),
            925 => array('id' => '930', 'title' => 'فومن', 'province_id' => '26'),
            926 => array('id' => '931', 'title' => 'کلاچای', 'province_id' => '26'),
            927 => array('id' => '932', 'title' => 'کوچصفهان', 'province_id' => '26'),
            928 => array('id' => '933', 'title' => 'کومله', 'province_id' => '26'),
            929 => array('id' => '934', 'title' => 'کیاشهر', 'province_id' => '26'),
            930 => array('id' => '935', 'title' => 'گوراب زرمیخ', 'province_id' => '26'),
            931 => array('id' => '936', 'title' => 'لاهیجان', 'province_id' => '26'),
            932 => array('id' => '937', 'title' => 'لشت نشا', 'province_id' => '26'),
            933 => array('id' => '938', 'title' => 'لنگرود', 'province_id' => '26'),
            934 => array('id' => '939', 'title' => 'لوشان', 'province_id' => '26'),
            935 => array('id' => '940', 'title' => 'لولمان', 'province_id' => '26'),
            936 => array('id' => '941', 'title' => 'لوندویل', 'province_id' => '26'),
            937 => array('id' => '942', 'title' => 'لیسار', 'province_id' => '26'),
            938 => array('id' => '943', 'title' => 'ماسال', 'province_id' => '26'),
            939 => array('id' => '944', 'title' => 'ماسوله', 'province_id' => '26'),
            940 => array('id' => '945', 'title' => 'مرجقل', 'province_id' => '26'),
            941 => array('id' => '946', 'title' => 'منجیل', 'province_id' => '26'),
            942 => array('id' => '947', 'title' => 'واجارگاه', 'province_id' => '26'),
            943 => array('id' => '948', 'title' => 'امیرکلا', 'province_id' => '27'),
            944 => array('id' => '949', 'title' => 'ایزدشهر', 'province_id' => '27'),
            945 => array('id' => '950', 'title' => 'آلاشت', 'province_id' => '27'),
            946 => array('id' => '951', 'title' => 'آمل', 'province_id' => '27'),
            947 => array('id' => '952', 'title' => 'بابل', 'province_id' => '27'),
            948 => array('id' => '953', 'title' => 'بابلسر', 'province_id' => '27'),
            949 => array('id' => '954', 'title' => 'بلده', 'province_id' => '27'),
            950 => array('id' => '955', 'title' => 'بهشهر', 'province_id' => '27'),
            951 => array('id' => '956', 'title' => 'بهنمیر', 'province_id' => '27'),
            952 => array('id' => '957', 'title' => 'پل سفید', 'province_id' => '27'),
            953 => array('id' => '958', 'title' => 'تنکابن', 'province_id' => '27'),
            954 => array('id' => '959', 'title' => 'جویبار', 'province_id' => '27'),
            955 => array('id' => '960', 'title' => 'چالوس', 'province_id' => '27'),
            956 => array('id' => '961', 'title' => 'چمستان', 'province_id' => '27'),
            957 => array('id' => '962', 'title' => 'خرم آباد', 'province_id' => '27'),
            958 => array('id' => '963', 'title' => 'خلیل شهر', 'province_id' => '27'),
            959 => array('id' => '964', 'title' => 'خوش رودپی', 'province_id' => '27'),
            960 => array('id' => '965', 'title' => 'دابودشت', 'province_id' => '27'),
            961 => array('id' => '966', 'title' => 'رامسر', 'province_id' => '27'),
            962 => array('id' => '967', 'title' => 'رستمکلا', 'province_id' => '27'),
            963 => array('id' => '968', 'title' => 'رویان', 'province_id' => '27'),
            964 => array('id' => '969', 'title' => 'رینه', 'province_id' => '27'),
            965 => array('id' => '970', 'title' => 'زرگرمحله', 'province_id' => '27'),
            966 => array('id' => '971', 'title' => 'زیرآب', 'province_id' => '27'),
            967 => array('id' => '972', 'title' => 'ساری', 'province_id' => '27'),
            968 => array('id' => '973', 'title' => 'سرخرود', 'province_id' => '27'),
            969 => array('id' => '974', 'title' => 'سلمان شهر', 'province_id' => '27'),
            970 => array('id' => '975', 'title' => 'سورک', 'province_id' => '27'),
            971 => array('id' => '976', 'title' => 'شیرگاه', 'province_id' => '27'),
            972 => array('id' => '977', 'title' => 'شیرود', 'province_id' => '27'),
            973 => array('id' => '978', 'title' => 'عباس آباد', 'province_id' => '27'),
            974 => array('id' => '979', 'title' => 'فریدونکنار', 'province_id' => '27'),
            975 => array('id' => '980', 'title' => 'فریم', 'province_id' => '27'),
            976 => array('id' => '981', 'title' => 'قائم شهر', 'province_id' => '27'),
            977 => array('id' => '982', 'title' => 'کتالم', 'province_id' => '27'),
            978 => array('id' => '983', 'title' => 'کلارآباد', 'province_id' => '27'),
            979 => array('id' => '984', 'title' => 'کلاردشت', 'province_id' => '27'),
            980 => array('id' => '985', 'title' => 'کله بست', 'province_id' => '27'),
            981 => array('id' => '986', 'title' => 'کوهی خیل', 'province_id' => '27'),
            982 => array('id' => '987', 'title' => 'کیاسر', 'province_id' => '27'),
            983 => array('id' => '988', 'title' => 'کیاکلا', 'province_id' => '27'),
            984 => array('id' => '989', 'title' => 'گتاب', 'province_id' => '27'),
            985 => array('id' => '990', 'title' => 'گزنک', 'province_id' => '27'),
            986 => array('id' => '991', 'title' => 'گلوگاه', 'province_id' => '27'),
            987 => array('id' => '992', 'title' => 'محمودآباد', 'province_id' => '27'),
            988 => array('id' => '993', 'title' => 'مرزن آباد', 'province_id' => '27'),
            989 => array('id' => '994', 'title' => 'مرزیکلا', 'province_id' => '27'),
            990 => array('id' => '995', 'title' => 'نشتارود', 'province_id' => '27'),
            991 => array('id' => '996', 'title' => 'نکا', 'province_id' => '27'),
            992 => array('id' => '997', 'title' => 'نور', 'province_id' => '27'),
            993 => array('id' => '998', 'title' => 'نوشهر', 'province_id' => '27'),
            994 => array('id' => '999', 'title' => 'اراک', 'province_id' => '28'),
            995 => array('id' => '1000', 'title' => 'آستانه', 'province_id' => '28'),
            996 => array('id' => '1001', 'title' => 'آشتیان', 'province_id' => '28'),
            997 => array('id' => '1002', 'title' => 'پرندک', 'province_id' => '28'),
            998 => array('id' => '1003', 'title' => 'تفرش', 'province_id' => '28'),
            999 => array('id' => '1004', 'title' => 'توره', 'province_id' => '28'),
            1000 => array('id' => '1005', 'title' => 'جاورسیان', 'province_id' => '28'),
            1001 => array('id' => '1006', 'title' => 'خشکرود', 'province_id' => '28'),
            1002 => array('id' => '1007', 'title' => 'خمین', 'province_id' => '28'),
            1003 => array('id' => '1008', 'title' => 'خنداب', 'province_id' => '28'),
            1004 => array('id' => '1009', 'title' => 'داودآباد', 'province_id' => '28'),
            1005 => array('id' => '1010', 'title' => 'دلیجان', 'province_id' => '28'),
            1006 => array('id' => '1011', 'title' => 'رازقان', 'province_id' => '28'),
            1007 => array('id' => '1012', 'title' => 'زاویه', 'province_id' => '28'),
            1008 => array('id' => '1013', 'title' => 'ساروق', 'province_id' => '28'),
            1009 => array('id' => '1014', 'title' => 'ساوه', 'province_id' => '28'),
            1010 => array('id' => '1015', 'title' => 'سنجان', 'province_id' => '28'),
            1011 => array('id' => '1016', 'title' => 'شازند', 'province_id' => '28'),
            1012 => array('id' => '1017', 'title' => 'غرق آباد', 'province_id' => '28'),
            1013 => array('id' => '1018', 'title' => 'فرمهین', 'province_id' => '28'),
            1014 => array('id' => '1019', 'title' => 'قورچی باشی', 'province_id' => '28'),
            1015 => array('id' => '1020', 'title' => 'کرهرود', 'province_id' => '28'),
            1016 => array('id' => '1021', 'title' => 'کمیجان', 'province_id' => '28'),
            1017 => array('id' => '1022', 'title' => 'مامونیه', 'province_id' => '28'),
            1018 => array('id' => '1023', 'title' => 'محلات', 'province_id' => '28'),
            1019 => array('id' => '1024', 'title' => 'مهاجران', 'province_id' => '28'),
            1020 => array('id' => '1025', 'title' => 'میلاجرد', 'province_id' => '28'),
            1021 => array('id' => '1026', 'title' => 'نراق', 'province_id' => '28'),
            1022 => array('id' => '1027', 'title' => 'نوبران', 'province_id' => '28'),
            1023 => array('id' => '1028', 'title' => 'نیمور', 'province_id' => '28'),
            1024 => array('id' => '1029', 'title' => 'هندودر', 'province_id' => '28'),
            1025 => array('id' => '1030', 'title' => 'ابوموسی', 'province_id' => '29'),
            1026 => array('id' => '1031', 'title' => 'بستک', 'province_id' => '29'),
            1027 => array('id' => '1032', 'title' => 'بندرجاسک', 'province_id' => '29'),
            1028 => array('id' => '1033', 'title' => 'بندرچارک', 'province_id' => '29'),
            1029 => array('id' => '1034', 'title' => 'بندرخمیر', 'province_id' => '29'),
            1030 => array('id' => '1035', 'title' => 'بندرعباس', 'province_id' => '29'),
            1031 => array('id' => '1036', 'title' => 'بندرلنگه', 'province_id' => '29'),
            1032 => array('id' => '1037', 'title' => 'بیکا', 'province_id' => '29'),
            1033 => array('id' => '1038', 'title' => 'پارسیان', 'province_id' => '29'),
            1034 => array('id' => '1039', 'title' => 'تخت', 'province_id' => '29'),
            1035 => array('id' => '1040', 'title' => 'جناح', 'province_id' => '29'),
            1036 => array('id' => '1041', 'title' => 'حاجی آباد', 'province_id' => '29'),
            1037 => array('id' => '1042', 'title' => 'درگهان', 'province_id' => '29'),
            1038 => array('id' => '1043', 'title' => 'دهبارز', 'province_id' => '29'),
            1039 => array('id' => '1044', 'title' => 'رویدر', 'province_id' => '29'),
            1040 => array('id' => '1045', 'title' => 'زیارتعلی', 'province_id' => '29'),
            1041 => array('id' => '1046', 'title' => 'سردشت', 'province_id' => '29'),
            1042 => array('id' => '1047', 'title' => 'سندرک', 'province_id' => '29'),
            1043 => array('id' => '1048', 'title' => 'سوزا', 'province_id' => '29'),
            1044 => array('id' => '1049', 'title' => 'سیریک', 'province_id' => '29'),
            1045 => array('id' => '1050', 'title' => 'فارغان', 'province_id' => '29'),
            1046 => array('id' => '1051', 'title' => 'فین', 'province_id' => '29'),
            1047 => array('id' => '1052', 'title' => 'قشم', 'province_id' => '29'),
            1048 => array('id' => '1053', 'title' => 'قلعه قاضی', 'province_id' => '29'),
            1049 => array('id' => '1054', 'title' => 'کنگ', 'province_id' => '29'),
            1050 => array('id' => '1055', 'title' => 'کوشکنار', 'province_id' => '29'),
            1051 => array('id' => '1056', 'title' => 'کیش', 'province_id' => '29'),
            1052 => array('id' => '1057', 'title' => 'گوهران', 'province_id' => '29'),
            1053 => array('id' => '1058', 'title' => 'میناب', 'province_id' => '29'),
            1054 => array('id' => '1059', 'title' => 'هرمز', 'province_id' => '29'),
            1055 => array('id' => '1060', 'title' => 'هشتبندی', 'province_id' => '29'),
            1056 => array('id' => '1061', 'title' => 'ازندریان', 'province_id' => '30'),
            1057 => array('id' => '1062', 'title' => 'اسدآباد', 'province_id' => '30'),
            1058 => array('id' => '1063', 'title' => 'برزول', 'province_id' => '30'),
            1059 => array('id' => '1064', 'title' => 'بهار', 'province_id' => '30'),
            1060 => array('id' => '1065', 'title' => 'تویسرکان', 'province_id' => '30'),
            1061 => array('id' => '1066', 'title' => 'جورقان', 'province_id' => '30'),
            1062 => array('id' => '1067', 'title' => 'جوکار', 'province_id' => '30'),
            1063 => array('id' => '1068', 'title' => 'دمق', 'province_id' => '30'),
            1064 => array('id' => '1069', 'title' => 'رزن', 'province_id' => '30'),
            1065 => array('id' => '1070', 'title' => 'زنگنه', 'province_id' => '30'),
            1066 => array('id' => '1071', 'title' => 'سامن', 'province_id' => '30'),
            1067 => array('id' => '1072', 'title' => 'سرکان', 'province_id' => '30'),
            1068 => array('id' => '1073', 'title' => 'شیرین سو', 'province_id' => '30'),
            1069 => array('id' => '1074', 'title' => 'صالح آباد', 'province_id' => '30'),
            1070 => array('id' => '1075', 'title' => 'فامنین', 'province_id' => '30'),
            1071 => array('id' => '1076', 'title' => 'فرسفج', 'province_id' => '30'),
            1072 => array('id' => '1077', 'title' => 'فیروزان', 'province_id' => '30'),
            1073 => array('id' => '1078', 'title' => 'قروه درجزین', 'province_id' => '30'),
            1074 => array('id' => '1079', 'title' => 'قهاوند', 'province_id' => '30'),
            1075 => array('id' => '1080', 'title' => 'کبودر آهنگ', 'province_id' => '30'),
            1076 => array('id' => '1081', 'title' => 'گل تپه', 'province_id' => '30'),
            1077 => array('id' => '1082', 'title' => 'گیان', 'province_id' => '30'),
            1078 => array('id' => '1083', 'title' => 'لالجین', 'province_id' => '30'),
            1079 => array('id' => '1084', 'title' => 'مریانج', 'province_id' => '30'),
            1080 => array('id' => '1085', 'title' => 'ملایر', 'province_id' => '30'),
            1081 => array('id' => '1086', 'title' => 'نهاوند', 'province_id' => '30'),
            1082 => array('id' => '1087', 'title' => 'همدان', 'province_id' => '30'),
            1083 => array('id' => '1088', 'title' => 'ابرکوه', 'province_id' => '31'),
            1084 => array('id' => '1089', 'title' => 'احمدآباد', 'province_id' => '31'),
            1085 => array('id' => '1090', 'title' => 'اردکان', 'province_id' => '31'),
            1086 => array('id' => '1091', 'title' => 'اشکذر', 'province_id' => '31'),
            1087 => array('id' => '1092', 'title' => 'بافق', 'province_id' => '31'),
            1088 => array('id' => '1093', 'title' => 'بفروئیه', 'province_id' => '31'),
            1089 => array('id' => '1094', 'title' => 'بهاباد', 'province_id' => '31'),
            1090 => array('id' => '1095', 'title' => 'تفت', 'province_id' => '31'),
            1091 => array('id' => '1096', 'title' => 'حمیدیا', 'province_id' => '31'),
            1092 => array('id' => '1097', 'title' => 'خضرآباد', 'province_id' => '31'),
            1093 => array('id' => '1098', 'title' => 'دیهوک', 'province_id' => '31'),
            1094 => array('id' => '1099', 'title' => 'زارچ', 'province_id' => '31'),
            1095 => array('id' => '1100', 'title' => 'شاهدیه', 'province_id' => '31'),
            1096 => array('id' => '1101', 'title' => 'طبس', 'province_id' => '31'),
            1097 => array('id' => '1103', 'title' => 'عقدا', 'province_id' => '31'),
            1098 => array('id' => '1104', 'title' => 'مروست', 'province_id' => '31'),
            1099 => array('id' => '1105', 'title' => 'مهردشت', 'province_id' => '31'),
            1100 => array('id' => '1106', 'title' => 'مهریز', 'province_id' => '31'),
            1101 => array('id' => '1107', 'title' => 'میبد', 'province_id' => '31'),
            1102 => array('id' => '1108', 'title' => 'ندوشن', 'province_id' => '31'),
            1103 => array('id' => '1109', 'title' => 'نیر', 'province_id' => '31'),
            1104 => array('id' => '1110', 'title' => 'هرات', 'province_id' => '31'),
            1105 => array('id' => '1111', 'title' => 'یزد', 'province_id' => '31'),
            1106 => array('id' => '1116', 'title' => 'پرند', 'province_id' => '8'),
            1107 => array('id' => '1117', 'title' => 'فردیس', 'province_id' => '5'),
            1108 => array('id' => '1118', 'title' => 'مارلیک', 'province_id' => '5'),
            1109 => array('id' => '1119', 'title' => 'سادات شهر', 'province_id' => '27'),
            1110 => array('id' => '1121', 'title' => 'زیباکنار', 'province_id' => '26'),
            1111 => array('id' => '1135', 'title' => 'کردان', 'province_id' => '5'),
            1112 => array('id' => '1137', 'title' => 'ساوجبلاغ', 'province_id' => '5'),
            1113 => array('id' => '1138', 'title' => 'تهران دشت', 'province_id' => '5'),
            1114 => array('id' => '1150', 'title' => 'گلبهار', 'province_id' => '11'),
            1115 => array('id' => '1153', 'title' => 'قیامدشت', 'province_id' => '8'),
            1116 => array('id' => '1155', 'title' => 'بینالود', 'province_id' => '11'),
            1117 => array('id' => '1159', 'title' => 'پیربازار', 'province_id' => '26'),
            1118 => array('id' => '1160', 'title' => 'رضوانشهر', 'province_id' => '31'),
            1119 => array('id' => '1161', 'title' => 'فریدن', 'province_id' => '4'),
            1120 => array('id' => '1162', 'title' => 'دشتی', 'province_id' => '7'),
            1121 => array('id' => '1163', 'title' => 'شمیرانات', 'province_id' => '8'),
            1122 => array('id' => '1164', 'title' => 'کوهرنگ', 'province_id' => '9'),
            1123 => array('id' => '1165', 'title' => 'تفتان', 'province_id' => '16'),
            1124 => array('id' => '1166', 'title' => 'دلگان', 'province_id' => '16'),
            1125 => array('id' => '1167', 'title' => 'سب و سوران', 'province_id' => '16'),
            1126 => array('id' => '1168', 'title' => 'خفر', 'province_id' => '17'),
            1127 => array('id' => '1169', 'title' => 'رستم آباد', 'province_id' => '17'),
            1128 => array('id' => '1170', 'title' => 'سرچهان', 'province_id' => '17'),
            1129 => array('id' => '1171', 'title' => 'میاندرود', 'province_id' => '27'),
            1130 => array('id' => '1172', 'title' => 'هلیلان', 'province_id' => '6'),
            1131 => array('id' => '1173', 'title' => 'سیروان', 'province_id' => '6'),
        );
        foreach ($data as $item){
            City::create($item);
        }
        $data2 = array(
            0 => array('id' => '1', 'title' => 'آذربایجان شرقی'),
            1 => array('id' => '2', 'title' => 'آذربایجان غربی'),
            2 => array('id' => '3', 'title' => 'اردبیل'),
            3 => array('id' => '4', 'title' => 'اصفهان'),
            4 => array('id' => '5', 'title' => 'البرز'),
            5 => array('id' => '6', 'title' => 'ایلام'),
            6 => array('id' => '7', 'title' => 'بوشهر'),
            7 => array('id' => '8', 'title' => 'تهران'),
            8 => array('id' => '9', 'title' => 'چهارمحال و بختیاری'),
            9 => array('id' => '10', 'title' => 'خراسان جنوبی'),
            10 => array('id' => '11', 'title' => 'خراسان رضوی'),
            11 => array('id' => '12', 'title' => 'خراسان شمالی'),
            12 => array('id' => '13', 'title' => 'خوزستان'),
            13 => array('id' => '14', 'title' => 'زنجان'),
            14 => array('id' => '15', 'title' => 'سمنان'),
            15 => array('id' => '16', 'title' => 'سیستان و بلوچستان'),
            16 => array('id' => '17', 'title' => 'فارس'),
            17 => array('id' => '18', 'title' => 'قزوین'),
            18 => array('id' => '19', 'title' => 'قم'),
            19 => array('id' => '20', 'title' => 'کردستان'),
            20 => array('id' => '21', 'title' => 'کرمان'),
            21 => array('id' => '22', 'title' => 'کرمانشاه'),
            22 => array('id' => '23', 'title' => 'کهگیلویه و بویراحمد'),
            23 => array('id' => '24', 'title' => 'گلستان'),
            24 => array('id' => '25', 'title' => 'لرستان'),
            25 => array('id' => '26', 'title' => 'گیلان'),
            26 => array('id' => '27', 'title' => 'مازندران'),
            27 => array('id' => '28', 'title' => 'مرکزی'),
            28 => array('id' => '29', 'title' => 'هرمزگان'),
            29 => array('id' => '30', 'title' => 'همدان'),
            30 => array('id' => '31', 'title' => 'یزد'),
        );
        foreach ($data2 as $item2){
            Province::create($item2);
        }
    }


}
